### ISSUE TITLE
Now including comments on chap 2

### ISSUE THREAD

**Issue by JBwell** [bitcoinbook/bitcoinbook#10]
Hi, Have just reviewed chap 2 and tried to put some comments in there. Again, review is from a beginner's perspective. Regards, James

**Comment by enderminh** [comment]
Thanks James for writing the comments. I see the many comments you have in chapter 1 as well as chapter 2 in your actual pull request (https://github.com/aantonop/bitcoinbook/pull/9).

I haven't merged that pull request, as they contain many questions/comments that are not meant to be merged in, but rather addressed by Andreas. He'll review them in the future.

In the future, it might be easier to file discussions/philosophical questions you have as issues, and only use git commits for actual changes to the final text (similar how you don't commit discussions/questions on the actual Wikipedia pages, but use the discussion page instead).

Thanks!
