### ISSUE TITLE
Chapter 9: Suggestion to Mention Coinye

### ISSUE THREAD

**Issue by 0xmichalis** [bitcoinbook/bitcoinbook#112]
http://en.wikipedia.org/wiki/Coinye
Probably the first coin that was abandoned due to filing of a trademark infringement lawsuit against its creators.

**Comment by bombsite** [comment]
Disagree. The book should be facilitating the understanding of btc in the most concise way possible. Adding bloat like this will only thin out the meaningful content.

**Comment by 0xmichalis** [comment]
How ~10 lines of writing in the Alternative Currencies chapter will add bloat and make the content of the book less meaningful? The story of this currency benefits other cryptocurrencies since it is an example-to-be-avoided case. 

Anyway, that's @aantonop's call.

**Comment by bryceweiner** [comment]
I think it's a valid point in that it shows that there are regulatory and legal issues involving cryptocurrencies that bitcoin simply will not face but may have to deal with the consequences.

**Comment by mikong** [comment]
I think Coinye is not among the alt-coins worth mentioning in this book. The trademark infringement lawsuit is an interesting trivia, but unless it helps in the narrative of this chapter or in other parts of the book, it seems like a distraction. I can imagine a book where there's a trivia box where this is mentioned and that can work but this particular book doesn't have those trivia boxes.

Perhaps it can work in a chapter about regulation, but so far, such chapter isn't planned in this book. I doubt such chapter can be helpful given that it's still very early and regulations are still being formulated. Also, the topic of regulation simply doesn't belong in this technical Bitcoin book. IMHO.

Still, as @kargakis said, it's Andreas' call.

**Comment by bsecsystems** [comment]
Hey, I'm the original "creator" David and I think this is a good idea
