### ISSUE TITLE
`asciidoc` vs `markdown`

### ISSUE THREAD

**Issue by kostaz** [bitcoinbook/bitcoinbook#122]
### Question 1

Why asciidoc and github flavored markdown?
### Question 2

How to convert asciidoc to github flavored markdown?

**Comment by enderminh** [comment]
Hi there,

   My guess is that this is going to turn into a real book, and asciidoc probably lends itself better to the book-publishing requirements from O'Reilly. Github flavored markdown seems to be optimized for code. However, this is just my wild guess.

   However, given that all this book is written in asciidoc, I think it's unlikely that we are going to switch it over to GFM. I don't know if there are asciidoc->GFM converters out there, but GitHub already displays ASCII doc nicely for reading. Would that suffice for you for reading and contributing?

   Closing this "bug" for now.

Thanks,
Minh.
