### ISSUE TITLE
Chapter 2: SPV is "Simplified payment verification"

### ISSUE THREAD

**Issue by biafra23** [bitcoinbook/bitcoinbook#123]
AFAIK SPV stands for "Simplified payment verification" and not "Simple payment verification".

**Comment by biafra23** [comment]
PR: https://github.com/aantonop/bitcoinbook/pull/124

**Comment by biafra23** [comment]
If you agree, to change this, I can create PRs for the other places where SPV is called Simple payment verification.

**Comment by enderminh** [comment]
I am closing this issue, since #124 is the pull request for that (which I am very likely going to merge in, thanks!).
