### ISSUE TITLE
Chapter 10: Suggestion to expand on Tails / Linux boot ISOs / 2FA / BIP39 / sweeping BIP 38 / secure paper wallet generation

### ISSUE THREAD

**Issue by aussiehash** [bitcoinbook/bitcoinbook#138]
Andreas, congratulations on your detailed book.  Bitcoin is a rapidly moving target and publications can become obsolete overnight.  I realize your book is not a "dummies" how-to guide

https://github.com/aantonop/bitcoinbook/blob/develop/ch10.asciidoc#hardware-wallets
https://github.com/aantonop/bitcoinbook/blob/develop/ch10.asciidoc#multi-sig-and-governance

These sections are critical, bitcoin loss/theft is bad publicity and might "radicalize" those new to bitcoin into harsh critics.

Perhaps an addendum chapter with further explanation, or links to Tails / Linux boot ISOs / [bitkey](https://github.com/bitkey/bitkey) etc for secure offline wallet generation, further discussion of insured online vaults, the use of strong passwords and 2fa authentication with such services, and more discussion on Trezor and similar hardware wallets coming to the market, and electrum/BIP39 mnemonic clients, and Armory lockboxes

Also a newbies section for sweeping BIP38 wallets, key things not to do, etc

http://bitzuma.com/posts/bitcoin-paper-wallets-from-scratch/
http://bitzuma.com/posts/five-ways-to-lose-money-with-bitcoin-change-addresses/

Also I don't know if your book has references to Coinbase's [Toshi](https://github.com/coinbase/toshi) or bitpay's [copay](https://github.com/bitpay/copay) [bitcore](https://github.com/bitpay/bitcore), but they should probably be in there.

**Comment by enderminh** [comment]
There is a lot of suggestions here and not a specific request, so I will ask to Andreas to review/close out as he sees fit.
