### ISSUE TITLE
Chapter 9: Suggestion to add Burstcoin for its concensus innovation

### ISSUE THREAD

**Issue by uraymeiviar** [bitcoinbook/bitcoinbook#140]
I think you should add Burstcoin which use Proof-Of-Capacity system, network use deadline to reach concensus based on nonce stored in miner's storage (instead of calculating it on the fly), which lead to capability to mine coin using hard drive (or any storage), the innovation is, its an efficient kind of mining, it doesn't use huge electricity as on GPU, its safe from botnet as CPU mining suffer and harddrive is cheaper unlike ASIC

**Comment by aantonop** [comment]
This will have to wait for the second edition of the book. We are past adding changes like this to the copy.

Thank you!
