### ISSUE TITLE
In chapter 2, about "encumbrance" and other concept in the same paragraph.

### ISSUE THREAD

**Issue by hungtuchen** [bitcoinbook/bitcoinbook#142]
```
A transaction output assigns a new owner to the value by associating it with a key. The destination key is called an **encumbrance**. It imposes a requirement for a signature for the funds to be redeemed in future transactions. Outputs from one transaction can be used as inputs in a new transaction, thus creating a chain of ownership as the value is moved from address to address.
```

I'm just new to this book, and find it fascinating.
In chapter 2, it mentioned encumbrance and other concept in this paragraph, but seems a little inconsistent with the context to me.
_output assigns a new owner to the value by associating it with a key_ 
What's the key here? Is it the hash related to the transaction?
_It imposes a requirement for a signature for the funds to be redeemed in future transactions._
In this place, signature from who? and redeemed from who and how does it work?

If further explanation could be supplied, I would appreciate.
I would give more feedback while going throughout this book, it's awesome.

**Comment by enderminh** [comment]
Thanks for the feedback, though the first few chapters are very introductionary to give the reader a big picture overview. You'll see that later chapters will go in much more technical detail what the key actually is, what signature means and how "this all works".
