### ISSUE TITLE
Chapter 3 : could it be any chance that the wallet is already encrypted?

### ISSUE THREAD

**Issue by hungtuchen** [bitcoinbook/bitcoinbook#149]
In ch3 , the first time I tried to type this command: 

```
bitcoin-cli encryptwallet ----------
```

but it shows

```
error: {"code":-15,"message":"Error: running with an encrypted wallet, but encryptwallet was called."}
```

and I looked back to the first time I type 

```
bitcoin-cli getinfo
```

```
"unlocked_until" : 0
```

 this line has already existed.

Could it be any chance that this situation happens, that I could messed up somewhere else?
Because I have totally no idea about it.

**Comment by enderminh** [comment]
It sounds like your wallet was already encrypted before when you tried to encrypt it again. Closing this since it's not an "issue/suggestion" with the book's content.

**Comment by hungtuchen** [comment]
Of course it is the case. I can read it.
As part of the question, I followed the steps as the book instructed.
So it turn outs to be different, so that's why I'm asking Is it "any chance other thing happened?"
Maybe other people who read the book will face this situation, Isn't it a issue or suggestion?
