### ISSUE TITLE
Comments and Corrections from Minh

### ISSUE THREAD

**Issue by aantonop** [bitcoinbook/bitcoinbook#17]
# 

In chapter 1, "Getting started" you write

"Conversely, if a user has a full client without adequate backups, they may lose their funds through a computer mishap. "

I suggest changing "they" into "he or she", since in the first sentence you used the singular form of "user".
# 

In chapter 1, "Quick Start", you write

"she opens the blockchain.info wallet page at https://blockchain.info/wallet and selects "Start a New Wallet""

Note that on the actual blockchain.info/wallet page, the A in "Start A New Wallet" is capitalized, whereas in your book it's not. I suggest actually fixing the website button for consistency.
# 

In chapter 2, "Buying a cup of coffee", you write

a "payment request" is a QR encoded URL that contains a destination address, a payment amount and a generic description such as "Bob's Cafe"

In your payment URL example it actually has four things. Do you want to mention that recipient label as well?
# 

In chapter 2, "Bitcoin mining", you write

"as this book is written, by 2014, the difficulty is so high that it is only profitable to mine with Application Specific Integrated Circuits, essentially hundreds of mining algorithms printed in hardware"

I recommend putting the abbreviation (ASIC) after you use the word Application Specific Integrated Circuits for the first time here, especially because you use the abbreviation later in the paragraph.
# 

In chapter 3, at the end of the "Compiling the client from the source code" chapter you used a different password in the bitcoin configuration file than the one that bitcoind recommended.

Bitcoind suggested

rpcuser=bitcoinrpc
rpcpassword=2XA4DuKNCbtZXsBQRRNDEwEY2nM6M4H9Tx5dFjoAVVbK

but the bitcoin.conf you created has

rpcuser=bitcoinrpc
rpcpassword=7p687uGU8wMyBprB2aQrnt72r9Lh6jZy

Why? I understand we don't want the reader to actually use that specific password as printed in this book, but the example should be coherent.
# 

In chapter 3, you write

"Since the transaction sending this bitcoin was only sent in the last few seconds, it has still not confirmed and therefore we will see it list a zero balance:"

This is the example you written about calling "getreceivedbyaddress" without the second parameter, pointing out that it uses the minconf in the configuration. You should point out the default value of this configuration, and that it is _not_ zero, which is why you don't see the balance yet.
# 

In chapter 3, in the tip about transaction malleability, you should say how many confirmations are required until the txid can be considered final. Is it only 1?
# 

In chapter 3, you write the nth block usually with an apostrophe like 286384'th block or 0'th block. I don't think that's grammatically correct. It should be 286384th block or 0th block, the same reason why we say 5th amendment and not 5'th amendment.
# 

In chapter 3, you write

First, we generate a "seed" that will be used as the basis to derive a chain of keys, compatible with the Electrum wallet and other similar implementations.

This is the first time you mentioned Electrum to the user, so I think it deserves some explanation of what Electrum is (or maybe just use the generic term of deterministic wallets?).
# 

In chapter 4, you have this tip listed twice:

The bitcoin private key is just a number. A public key can be generated from any private key. Therefore, a public key can be generated from any number, up to 256-bits long. You can pick your keys randomly using a method as simple as dice, pencil and paper.
# 

In chapter 4, you mention this sentence twice:

Many software implementations of bitcoin use the OpenSSL library, specifically the Elliptic Curve library.
# 

In chapter 4, you have this tip listed twice:

The size of bitcoin's private key, 2^256^ is a truly unfathomable number. It is equal to approximately 10^77^ in decimal. The visible universe contains approximately 10^80^ atoms.
# 

In chapter 4, Figure 1 displays addresses in a Type-0 non-deterministic wallet. However, in there you have four addresses that actually have the same 256-bit random number and bitcoin address. Instead, you should have four different random numbers and addresses.

The same problem applies to the figure for Type-2 chained deterministic keys.
# 

In Chapter 4, Figure 6, you have a graph of Elliptic Curve Cryptography and describe that "Elliptic curve multiplication can be visualized geometrically as drawing a line connecting two points on the curve (G and kG) to produce a third point (K)".

However, the graph that you have uses the points P, Q, R and -R. Instead can you have a graph using the G, kG and K points instead?
#

**Comment by enderminh** [comment]
For better manageability, I am forking out this issue into several smaller sub-issues. This way, Andreas can address/close/reject them independently.

They got forked into the following issues:
https://github.com/aantonop/bitcoinbook/issues/19 - Payment request URL has four fields, but only three are described
https://github.com/aantonop/bitcoinbook/issues/20 - We should point out default value of minconf when calling getreceivedbyaddress without second parameter
https://github.com/aantonop/bitcoinbook/issues/21 - Multiple sentences and tips are repeated twice
https://github.com/aantonop/bitcoinbook/issues/22 - Wallet images should use different bitcoin addresses
https://github.com/aantonop/bitcoinbook/issues/23 - Example graph about Elliptic Curve Cryptography should use the same point labels as expressed in the text

The remaining trivial ones have been merged (https://github.com/aantonop/bitcoinbook/commit/640b8b21505f12f825238cbf3647dc8061dab82e)
