### ISSUE TITLE
Chapter 2: Description of number of confirmations seems incorrect 

### ISSUE THREAD

**Issue by enderminh** [bitcoinbook/bitcoinbook#18]
In Chapter 2, Andreas writes

"A few minutes later, a new block, #277317 is mined by another miner. As this new block is based on the previous block (#277316) that contained Alice's transaction, it added even more computation on top of that block, thereby strengthening the trust in those transactions. One block mined on top of the one containing the transaction is called "one confirmation" for that transaction. As the blocks pile on top of each other, it becomes exponentially harder to reverse the transaction, thereby making it more and more trusted by the network."

This could be a misleading, because once a transaction is included in a block, it would be considered to have 1 confirmation. In Andreas' example block #277317 actually makes up the _second_ confirmation. 

This was reported by erikwam's comment in pull request
https://github.com/erikwam/bitcoinbook/commit/80c0b6a9f9206ff6fd2b1e81e3b940d896840f78, though I have not accepted his commit, and leave this up to Andreas.

**Comment by winchell** [comment]
+1

**Comment by aantonop** [comment]
Yes, you are correct, I am incorrect in this description. The block containing the transaction is one confirmation, additional blocks on top serve as additional confirmations

**Comment by erikwam** [comment]
The following places should probably be changed also:

Chapter 2, the text above Figure 9:
The text:  "...The blocks above count as “confirmations”..." could be something like: "..The blocks above count as additional “confirmations”...""

Chapter 3, the text int the "tip box":
"Transaction IDs are not authoritative until a transaction has been confirmed. Absence of a transaction hash in the blockchain does not mean the transaction was not processed. This is known as "transaction malleability", as transaction hashes can be modified prior to confirmation in a block. After confirmation, the txid is immutable and authoritative."

if the transaction hashes should be modified before confirmation, it must be done _before_ it's included in the blockchain (assuming that the blockchain only contains confirmed blocks).
