### ISSUE TITLE
is the address a pubkey or hash of a pubkey

### ISSUE THREAD

**Issue by junfx** [bitcoinbook/bitcoinbook#193]
In ch4->introduction->private and public keys, said:

> from the public key(K), we use one-way ...hash ... to generate a bitcoin address.

In ch4->introduction->Private keys->Generating a private key from a random number, said:

> use the getnewaddress command. For security reasons it displays the public key only.

**Comment by wizardofozzie** [comment]
both. It _displays_ the public key only, but the private key (and public key) are both _saved_ in the database. 
Address is derived from pubkey.

```
Private key ==> public key <===> address
```

**Comment by junfx** [comment]
@wizardofozzie As I read further, I'm sure that the _getnewaddress_ displays an address, which derived from **one or more** pubkeys.
