### ISSUE TITLE
(Chapter 3) Error in the example depection that is shown

### ISSUE THREAD

**Issue by jgmGit** [bitcoinbook/bitcoinbook#195]
The following part in chapter 3 seems to be wrong. In the `bitcoin-cli sendrawtransaction` towards the end of the raw transaction you have entered the transaction hash(txid) 

`ae74538baa914f3799081ba78429d5d84f36a0127438e9f721dff584ac17b346` which you will get only after executing the `sendrawtransaction` command right ?

I can create a pull request if its an error.

The following is the part from the book where I feel its wrong.

Now it’s time to submit the newly created transaction to the network. We do that with the command sendrawtransaction, which takes the raw hex string produced by signrawtransaction. This is the same string we just decoded:

`$ bitcoin-cli sendrawtransaction 0100000001e34ac1e2baac09c366fce1c2245536bda8
f7db0f6685862aecf53ebd69f9a89c000000006a47304402203e8a16522da80cef66bacfbc0c8
00c6d52c4a26d1d86a54e0a1b76d661f020c9022010397f00149f2a8fb2bc5bca52f2d7a7f87e
3897a273ef54b277e4af52051a06012103c9700559f690c4a9182faa8bed88ad8a0c563777ac1
d3f00fd44ea6c71dc5127ffffffff02a0252600000000001976a914d90d36e98f62968d2bc9bb
d68107564a156a9bcf88ac50622500000000001976a91407bdb518fa2e6089fd810235cf1100c
9c13d1fd288ac00000000ae74538baa914f3799081ba78429d5d84f36a0127438e9f721dff584ac17b346`

The command sendrawtransaction returns a transaction hash (txid) as it submits the transaction on the network. We can now query that transaction ID with gettransaction:

`$ bitcoin-cli gettransaction ae74538baa914f3799081ba78429d5d84f36a0127438e9f7↵
21dff584ac17b346`

**Comment by wbnns** [comment]
@johnygeorge Hello, please submit this via the book's [errata page](http://www.oreilly.com/catalog/errata.csp?isbn=0636920032281) on O'Reilly.com.
