### ISSUE TITLE
Add "how to render" section in Readme.md

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [bitcoinbook/bitcoinbook#196]
Could you maybe add a command how this can be rendered to a pdf?
I saw that it uses asciidoc for rendering, but I dont understand what exactly I have to write... 

Could you maybe add an example?
Thanks!

**Comment by wbnns** [comment]
@lichtamberg Hello, I submitted PR #198 that resolves this issue. You can read _Mastering Bitcoin_ online for free at [O'Reilly.com](http://chimera.labs.oreilly.com/books/1234000001802). If you'd like a DRM-free PDF version - an Ebook - that option is available ([for purchase](http://shop.oreilly.com/product/0636920032281.do?intcmp=il-npa-books-video-product_chimera)) there as well. 👍

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hi @wbinns, I would like to print out the book by my own, so I would really prefer a PDF version - and not buy it.. Is it really so complicated to render it as pdf?

**Comment by bclermont** [comment]
@lichtamberg 

```
sudo apt-get install asciidoc
a2x -f epub book.asciidoc -d book -L
```

I just loaded on my android phone with Aldiko, render totally fine, so far

I guess you can do the same with `.pdf` format

**Comment by mbaniasad** [comment]
I would suggest adding this to main README.MD file

**Comment by skywinder** [comment]
@bclermont  got error
> a2x -f epub book.asciidoc -d book -L
```a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0 --stringparam toc.section.depth 1 --stringparam chunk.section.depth 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/epub.xsl" "~/bitcoinbook/book.xml" returned non-zero exit status 5```

a2x version 8.6.9

**Comment by varung** [comment]
The resulting epub from 
```a2x -f epub book.asciidoc -d book -L```
renders lists and a tags oddly (i.e., it doesn't turn them into links)

Also, omitting "-L" to as2x results in several xmllint errors.
