### ISSUE TITLE
Chapter 5 seems to overly confuse addresses with keys

### ISSUE THREAD

**Issue by luke-jr** [bitcoinbook/bitcoinbook#199]
UTXOs aren't tied to addresses, but only to the script the address translates to (which may or may not be related to the user the address represents).

**Comment by aantonop** [comment]
Thanks Luke.  I'm rewriting chapter 5 right now.  Can you propose language or point to specific areas that are examples of this issue?

**Comment by luke-jr** [comment]
Probably the cleanest way to handle this is to not mention addresses in the context of low-level blockchain transactions at all, and have a separate section (perhaps in the same chapter) explaining how the high-level concepts (such as addresses and balances) are mapped to the low-level concepts (such as keys, scripts, and UTXOs).

**Comment by aantonop** [comment]
Great suggestions, thanks.  Will make changes and then reference them in
this issue before closing it.

**Comment by wbnns** [comment]
@luke-jr Hi Luke, I hope you're doing well - just a quick heads up that this is still on the radar. 👍

**Comment by aantonop** [comment]
@luke-jr I've re-written a significant percentage of the chapter. I think it is much more clear now and I took your advice to add a section on how higher-level abstractions are derived from scripts, UTXO and keys. 

(It's now renamed to ch06, as I split a previous chapter. I've also split out a lot of stuff that was previously in the transaction chapter, which is now going into a new "advanced transactions" chapter 7)

See https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc

I would appreciate any comments you have and thanks for your input so far!

**Comment by wbnns** [comment]
@luke-jr Heya Luke, just wanted to ping you on this to see if you'd had a chance to check out the [updated chapter](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc) and if you had any additional comments with regard to this open issue. Hope you're doing well!
