### ISSUE TITLE
New edition cover proposals

### ISSUE THREAD

**Issue by fjrojasgarcia** [bitcoinbook/bitcoinbook#215]
I was wondering if there is any plan for a new book cover.
If it's still pending, I propose this conversation for any ideas.

**Comment by wbnns** [comment]
@fjrojasgarcia Hello, I'll leave this open as `pending` for `suggested content` just in case.

**Comment by aantonop** [comment]
The second-edition cover will only change slightly. I'm changing the subtitle of the book and it will have a little "2nd Edition" corner sash on the top-right.
