### ISSUE TITLE
Chapter 4: Wallet images should use different bitcoin addresses

### ISSUE THREAD

**Issue by enderminh** [bitcoinbook/bitcoinbook#22]
In chapter 4, Figure 1 (https://github.com/aantonop/bitcoinbook/blob/develop/images/type0_chain.png) displays addresses in a Type-0 non-deterministic wallet. However, in there you have four addresses that actually have the same 256-bit random number and bitcoin address. Instead, you should have four different random numbers and addresses.

The same problem applies to the figure for Type-2 chained deterministic keys (https://github.com/aantonop/bitcoinbook/blob/develop/images/type2_chain.png)

**Comment by aantonop** [comment]
Replaced figure with a more abstract Type-0 wallet representation
