### ISSUE TITLE
P2SH(P2WPKH/P2WSH) address fix

### ISSUE THREAD

**Issue by ghost** [bitcoinbook/bitcoinbook#228]
I came from [here](https://github.com/bcoin-org/bcoin/issues/115). I'm just trying to replicate the example [p2wpkh inside p2sh](https://github.com/bitcoinbook/bitcoinbook/blob/develop/segwit.asciidoc#pay-to-witness-public-key-hash-inside-pay-to-script-hash) for educative purposes with bcoin lib, but I can't get the resulting addresses match. Can you explain how are you generating the address, please? In the bcoin issue you can watch my code.

**Edit**: 
bitcointalk thread: https://bitcointalk.org/index.php?topic=1758855 some have suggested a book error, updating issue name.

My results (using the public key hash and script hash given):
In the P2SH(P2WPKH) case:

1) Create segwit program with the pubkeyhash and the version number provided in the book: 
Code:
`OP_0 0x14 0xab68025513c3dbd2f7b92a94e0581f5d50f654e7`

2) Getting the hash160 of 1) (not matching from here below):
Code:
`3e0547268b3b19288b3adef9719ec8659f4b2b0b`

3) Embedding 2) in a p2sh script: 
Code:
`OP_HASH160 0x14 0x3e0547268b3b19288b3adef9719ec8659f4b2b0b OP_EQUAL`

4) Obtaining the address from 3):
Code:
`37Lx99uaGn5avKBxiW26HjedQE3LrDCZru`

---- 
**Edit 2**: added p2wsh case
In the P2SH(P2WSH) case:

witness program: 
`OP_0 0x20 0x9592d601848d04b172905e0ddb0adde59f1590f1e553ffc81ddc4b0ed927dd73`

segwit program hash160: 
`86762607e8fe87c0c37740cddee880988b9455b2`

p2sh script: 
`OP_HASH160 0x14 0x86762607e8fe87c0c37740cddee880988b9455b2 OP_EQUAL`

address is 
`3Dwz1MXhM6EfFoJChHCxh1jWHb8GQqRenG`

**Comment by wbnns** [comment]
@PleaseMe Hello, thanks for opening this issue - we'll look into it.

**Comment by aantonop** [comment]
Yes, the HASH160 was incorrect and so the address was incorrect too. Thanks for the fix!

Resolved in 
https://github.com/bitcoinbook/bitcoinbook/commit/49e8b5653347b21ca9d2bf34384a5e0a21b5fa3e
https://github.com/bitcoinbook/bitcoinbook/blob/develop/appdx-future-segwit.asciidoc
