### ISSUE TITLE
Chapter 4: Example graph about Elliptic Curve Cryptography should use the same point labels as expressed in the text

### ISSUE THREAD

**Issue by enderminh** [bitcoinbook/bitcoinbook#23]
In Chapter 4, Figure 6, you have a graph of Elliptic Curve Cryptography and describe that "Elliptic curve multiplication can be visualized geometrically as drawing a line connecting two points on the curve (G and kG) to produce a third point (K)".

However, the graph that you have uses the points P, Q, R and -R. Instead can you have a graph using the G, kG and K points instead?

**Comment by aantonop** [comment]
New chart fixed this
