### ISSUE TITLE
Chapter 2: Figure 4:  The output transaction of value 0.0805 should actually be value 0.0850

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#25]
The output for transaction 82 is 0.0805 but should probably be 0.085 (or perhaps 0.0845 if a transaction fee should be included).

**Comment by enderminh** [comment]
You are correct. It should be 0.0850. Thanks for reporting.

Re-assigning to Andreas, since I don't have the source images.

https://github.com/aantonop/bitcoinbook/blob/develop/images/Transaction_Chain.png

**Comment by enderminh** [comment]
This is now fixed.
