### ISSUE TITLE
Incorrect Spelling of mitigate

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#251]
Both Colu and Open Assets systems use special colored-coin addresses to **mitigat** this risk and to ensure that colored coins are not sent to unaware wallets.

**Comment by wintercooled** [comment]
Changed - will submit change

**Comment by wintercooled** [comment]
Sorry githubbers - i can read and submit issues but don't know how to submit actual changes - so apologies for the issues I have raised for others to fix!

**Comment by wbnns** [comment]
@wintercooled Thank you. This is resolved, now.
