### ISSUE TITLE
Missing full stop

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#252]
No full stop at end of sentence:

The output containing the OP_RETURN is called the marker output

**Comment by wintercooled** [comment]
changed - will submit change

**Comment by wintercooled** [comment]
Sorry githubbers - i can read and submit issues but don't know how to submit actual changes - so apologies for the issues I have raised for others to fix!

**Comment by wbnns** [comment]
@wintercooled Fixed. Thanks!
