### ISSUE TITLE
Commitment Transaction timelock example omission

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#254]
This doesn't read very well and may omit something:

For example, commitment transaction 1 cannot be spent before 1000 blocks, then if commitment transaction 2 is timelocked to 995 blocks.

**Comment by wbnns** [comment]
@wintercooled We'll keep this issue open, too, since it relates to:
+ #258  
+ #257 
+ #253 

Thanks again for the help!

**Comment by aantonop** [comment]
revised in copy edit
