### ISSUE TITLE
First form of unidirectional payment channel (not 'The most form')

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#255]
Did you mean 'first form' in the sentence below?

The most form of unidirectional payment channel was demonstrated as a prototype video streaming application in 2015 by an Argentinian team of developers.

**Comment by wintercooled** [comment]
changed - will submit changes

**Comment by wintercooled** [comment]
Sorry githubbers - i can read and submit issues but don't know how to submit actual changes - so apologies for the issues I have raised for others to fix!

**Comment by wbnns** [comment]
@wintercooled No problem, we've got it covered. This is fixed. Thanks!
