### ISSUE TITLE
Asymmetric Revocable Commitments example inconsistency

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#257]
To make the example of Hitesh and Irene easier to understand and more consistent - the wording preceding the output code could be changed as below (suggested change in bold)

from:

Hitesh has a commitment transaction with two outputs. The first output pays Irene the 5 bitcoin she is owed immediately. The second output pays Hitesh the 5 bitcoin he is owed, but only after a timelock of 1000 blocks. **The transaction outputs look like this:**

to:

Hitesh has a commitment transaction with two outputs. The first output pays Irene the 5 bitcoin she is owed immediately. The second output pays Hitesh the 5 bitcoin he is owed, but only after a timelock of 1000 blocks. **The commitment transaction Hitesh holds (signed by Irene), looks like this:**

PS - also in the text preceding the example output code the word 'immediately' is in bold in the first paragraph but not in the second - suggesting the first output paying Irene is somehow highly priority than the second one paying Hitesh.

**Comment by wbnns** [comment]
@wintercooled Thanks. I'm leaving this open as well so that @aantonop can take a look. It appears there may be some incomplete content in this section, which relates to the other issues you opened:
+ #258  
+ #254 
+ #253

**Comment by aantonop** [comment]
fixed in copy edit
