### ISSUE TITLE
Incomplete 'Tip' side note in Hash Time Lock Contracts (HTLC)

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#258]
In the HTLC section the following tip is incomplete:

Tip       The hash function used…​.

**Comment by wbnns** [comment]
@wintercooled Thanks. I'm leaving this open so that @aantonop can take a look. It appears there may be some incomplete content in this section, which relates to the other issues you opened:
+ #257 
+ #254
+ #253

**Comment by aantonop** [comment]
fixed in copy edit
