### ISSUE TITLE
Chapter 2: Total number of BTC will be less then 21 million.

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#26]
It may be a good idea to mention somewhere that the total number of 21 million Bitcoins is just an approximate number. The exact number is 20.9999999769 (million).
(source https://en.bitcoin.it/wiki/Controlled_supply - See table with headline "Projected Bitcoins Long Term").

**Comment by enderminh** [comment]
I haven't pulled in this merge request yet, as I find it such a minute detail. Most documentation just rounds it up to 21 million. Maybe just a tiny footnote is sufficient, but I will leave this up to Andreas (bug already assigned to him)

**Comment by aantonop** [comment]
I will add a note about this in the mining chapter where I talk about the reward schedule and halving every 210,000 blocks. I will show the numbers in detail there. Thanks!
