### ISSUE TITLE
Routed Payment Channel - grammar elaborate by/elaborated upon by

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#260]
'elaborate by' should perhaps be 'elaborated upon by'?

Suggested changes in bold below:

The Lightning Network was first described by Joseph Poon and Thadeus Dryja in January 2016, building on the concept of payment channels as proposed and elaborate**d upon** by many others:

**Comment by wintercooled** [comment]
Changed - will submit changes

**Comment by wintercooled** [comment]
Sorry githubbers - i can read and submit issues but don't know how to submit actual changes - so apologies for the issues I have raised for others to fix!

**Comment by wbnns** [comment]
@wintercooled This is also now fixed. Thanks again.
