### ISSUE TITLE
Grammar - 'Alice LN node' should be 'Alice's LN node'

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#261]
Currently:

Alice LN node also has the ability to connect over the Internet to Eric’s LN node.

**Comment by wintercooled** [comment]
Changed - will submit changes

**Comment by wintercooled** [comment]
Sorry githubbers - i can read and submit issues but don't know how to submit actual changes - so apologies for the issues I have raised for others to fix!

**Comment by wbnns** [comment]
Fixed. Thank you.
