### ISSUE TITLE
Space needed before link in Lightning Network Transport & Routing section

### ISSUE THREAD

**Issue by wintercooled** [bitcoinbook/bitcoinbook#263]
Need a space between the full stop and the http link in the following:

In addition, nodes have a long-term public key that they use as an identifier and to authenticate each other.http://bitfury.com/content/5-white-papers-research/whitepaper_flare_an_approach_to_routing_in_lightning_network_7_7_2016.pdf

**Comment by wintercooled** [comment]
changed - will propose file change

**Comment by wintercooled** [comment]
Sorry githubbers - i can read and submit issues but don't know how to submit actual changes - so apologies for the issues I have raised for others to fix!

**Comment by wbnns** [comment]
@wintercooled Fixed, thank you.
