### ISSUE TITLE
getinfo has been deprecated in Core 0.14.0

### ISSUE THREAD

**Issue by dimitris-t** [bitcoinbook/bitcoinbook#268]
Per Core 0.14.0 release notes at https://bitcoin.org/en/release/v0.14.0 the 'getinfo' command has been deprecated and moved into other commands.

It is quoted 10 times in Chapter 3 and 1 time in Chapter 9.

**Comment by dimitris-t** [comment]
Testing `bitcoin-cli getinfo` on 0.14.0 shows it still works as before.

**Comment by wbnns** [comment]
@dimitris-t Hello, thanks anyway for trying to help!
