### ISSUE TITLE
bitcoin "is" vs "are"

### ISSUE THREAD

**Issue by dimitris-t** [bitcoinbook/bitcoinbook#270]
I understand there was an effort to replace bitcoins with bitcoin in several chapters. I found the following phrases that may need to be switched from "bitcoin are" to "bitcoin is". I am not sure what the author's intentions are so I did not create any pull requests.

Chapter 1:
1. Unlike traditional currencies, bitcoin are entirely virtual
2. Bitcoin are created 
3. The protocol also halves the rate at which new bitcoin are created every four years

Chapter 10:
1. Bitcoin are "minted"

**Comment by wbnns** [comment]
@dimitris-t Hey, I think if it's inferring a plural tense it should be `are` and if the singular context is being described, for example, the protocol itself, it should be `is`.
