### ISSUE TITLE
Chapter 4 – ”Generating a private key from a random number”

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#28]
The paragraph (last part) under this headline states that:
"If the result is less than n - 1, we have a suitable private key. If it is greater than n - 1, we simply try again with another random number."

But how about the case when the result equals n - 1 ? To be consistent with the rest of the paragraph, perhaps it should say:

"If the result is less than n - 1, we have a suitable private key. Otherwise, we simply try again with another random number."

**Comment by enderminh** [comment]
Sounds correct to me, so I made the change.
