### ISSUE TITLE
Transaction fee

### ISSUE THREAD

**Issue by aschattopadhyay** [bitcoinbook/bitcoinbook#289]
Hi there:

I am very new to Bitcoin/Blockchain.

In Chapter 02, it talks about transaction fee. However I realized that there was no such fee for Tx from Joe to Alice.

Why is there during the Tx between Alice and Bob?

Thanks and regards,
Anindya

**Comment by dimitris-t** [comment]
Hi, are you referring to the very first (from the bottom) 0.1 BTC transaction in https://blockexplorer.com/address/1Cdid9KFAaatwczBwBttQcwXYCpvK8h7FK ? Perhaps in December 2013 you could still do no-fee transactions.

**Comment by aschattopadhyay** [comment]
Yes you are right, when Joe transfers 0.10 bitcoin, also known as 100 millibits to Alice in exchange of USD 10.00.

So do you mean if the same transaction happens now, it will involve transaction fee like any other transaction?

**Comment by dimitris-t** [comment]
Yes. Andreas discusses Fees in https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc

Some links of interest:
http://bitcoinfees.21.co
https://medium.com/@spair/the-bitcoin-fee-market-4df1857d12b7
