### ISSUE TITLE
bitcoinbook.info down? "Error establishing a database connection"

### ISSUE THREAD

**Issue by joh-mue** [bitcoinbook/bitcoinbook#290]
bitcoinbook.info returns "Error establishing a database connection"

**Comment by wbnns** [comment]
@joh-mue Hello, thanks for the heads up - we're checking into it.

**Comment by wbnns** [comment]
@joh-mue Thanks again for bringing this to attention. There was a temporary issue which has since been resolved.

**Comment by joh-mue** [comment]
👌🏻 thank you for your work
