### ISSUE TITLE
changed curl result

### ISSUE THREAD

**Issue by dindinw** [bitcoinbook/bitcoinbook#294]
https://github.com/bitcoinbook/bitcoinbook/blame/develop/ch02.asciidoc#L157
the curl got different result, I think here need some note about why result is changed. otherwise reader might got some confuse. the original result was unconfirmed and unspent at the exact time.

**Comment by wbnns** [comment]
@dindinw Hello, thanks for the note. We'll check into this.

**Comment by aantonop** [comment]
Over time people have sent bitcoin to this address, so the output keeps changing. For sanity's sake, I will leave it as is, for now.
