### ISSUE TITLE
Chapter 4: Figure 7

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#30]
The text under the figure is:
“Type-1 Deterministic Wallet: A Chain of Keys Generated from a Seed”

Not totally sure about this, but I think that should be Type-2.

**Comment by enderminh** [comment]
I think Type-1 is correct.

In Type-1 a single seed is used to generate a sequence of keys.
In Type-2 the single seed is used to generate a master key from which a bunch of other keys are derived (hence hierarchical deterministic wallet), as shown in Figure 8.

I thought Electrum uses a Type-2 wallet, so the heading of Figure 7 might be wrong and might be tipping you off incorrectly, but let me verify this in a different issue/thread.

Sources:
https://en.bitcoin.it/wiki/Deterministic_wallet
https://bitcointalk.org/index.php?topic=19137.msg239768#msg239768

If you still think this should be Type-2, don't hesitate to re-open this bug.

**Comment by erikwam** [comment]
Okay - You are probably right.
