### ISSUE TITLE
Chapter 4: Figure 6 Base58Check Encoding has misleading SHA256 input

### ISSUE THREAD

**Issue by enderminh** [bitcoinbook/bitcoinbook#32]
The diagram in Chapter 4, Figure 6:
https://github.com/aantonop/bitcoinbook/blob/develop/images/Base58CheckEncoding.png
can be misleading, because it shows that the input of the double SHA256 function is just the number. 

In reality, the input of the double SHA256 is the (prefix + number).

Not sure how to best fix this in the graphic (maybe just duplicating the version box to the top row as well? Or get rid of the top row altogether and make the green arrow come straight out of the middle row?

Assigning to Andreas for now.

**Comment by aantonop** [comment]
I know this is wrong, I'm going to fix it with a new diagram

On Tue, May 27, 2014 at 3:19 AM, Minh T. Nguyen notifications@github.comwrote:

> The diagram in Chapter 4, Figure 6:
> 
> https://github.com/aantonop/bitcoinbook/blob/develop/images/Base58CheckEncoding.png
> can be misleading, because it shows that the input of the double SHA256
> function is just the number.
> 
> In reality, the input of the double SHA256 is the (prefix + number).
> 
> Not sure how to best fix this in the graphic (maybe just duplicating the
> version box to the top row as well? Or get rid of the top row altogether
> and make the green arrow come straight out of the middle row?
> 
> Assigning to Andreas for now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aantonop/bitcoinbook/issues/32
> .

## 

Andreas M. Antonopoulos
andreas@antonopoulos.com
Tel: +1 347 744 9404

**Comment by aantonop** [comment]
Fixed! Thanks
