### ISSUE TITLE
Chapter 1

### ISSUE THREAD

**Issue by jet24** [bitcoinbook/bitcoinbook#330]
"Every 10 minutes on average, someone is able to validate the transactions of the past 10 minutes and is rewarded with brand new bitcoin." Nowadays transactions can be queued up for hours and days, so saying "transactions of the past 10 minutes" is inaccurate.

"The protocol also halves the rate at which new bitcoin are created every four years" Imprecise. Halving is at specific block number and not at the whim of ticking clock.

"Bitcoin’s total market value is estimated at between $10 billion and $15 billion" Probably best omitted since it's a moving target.

"Alice has decided to convert $10 US dollars into bitcoin" Conversion implies that dollars are destroyed, but they are not. Trade or exchange would be better terms to use.

**Comment by aantonop** [comment]
Fixed some of the wording. Some of it is necessarily oversimplified because this is chapter 1
