### ISSUE TITLE
Awkward wording "3deadbeef" in SegWit chapter

### ISSUE THREAD

**Issue by Krellan** [bitcoinbook/bitcoinbook#331]
Awkward wording "3deadbeef" in a paragraph here:
https://github.com/bitcoinbook/bitcoinbook/blob/errata/appdx-future-segwit.asciidoc

Recommended replacement text: "this address"

BTW, this chapter is great! A coherent explanation of how SegWit works and why it is useful.

Josh

**Comment by aantonop** [comment]
This was a placeholder for the 3-address generated in the previous line. It has been fixed in the second print of the second edition
