### ISSUE TITLE
There is a ambiguous expression in Chapter 8 about "Difficulty".

### ISSUE THREAD

**Issue by esrever10** [bitcoinbook/bitcoinbook#333]
When I read this book, I have a problem in understanding the "Difficulty" in Chapter 8.

There is a equation of difficulty:

`New Difficulty = Old Difficulty * (Actual Time of Last 2016 Blocks / 20160 minutes)`

I feel confused.
According to the formula, if Actual Time was longer than 20160 minutes, the New Difficulty would be bigger than Old Difficulty, and then Actual Time would be longer and longer.

I think the better expression is:

`New Difficulty Target = Old Difficulty Target * (Actual Time of Last 2016 Blocks / 20160 minutes)`

**Comment by aantonop** [comment]
This has been fixed in the second edition:

"New Target = Old Target * (Actual Time of Last 2016 Blocks / 20160 minutes)"

The wording around "diffulty" and "target" has been changed throughout the chapter and this formula was corrected.
