### ISSUE TITLE
Chapter 4: Incorrect elliptical curve addition graph

### ISSUE THREAD

**Issue by bannerts** [bitcoinbook/bitcoinbook#34]
The graph showing G + G = 2G  derived from a tangent line from the point G continues the pattern of addition of 2G + 2G as a tangent but calls the result 3G instead of 4G.  This pattern continues.  

My understanding the tangent of G derives 2G.  2G is used to derive 4G, etc which is done 256 times to create the terms which should be added together (by drawing a line between points) based on each bit of the private key. 

This shows how the public key could be derived in approximately 512 addition processes or less.  The way it is currently displayed leads the reader to think it requires a lot more addition processes to calculate (in my opinion)

**Comment by enderminh** [comment]
I don't understand the math behind this, so will assign to Andreas for commenting.

Scott -- would you also mind describing the exact expected vs. actual graphic? What would you have expected the graphic to be like?

**Comment by bannerts** [comment]
The graph would stay the same in form, however instead of each term being
incremented as G, 2G, 3G, 4G, ... et as would be by the process of simply
adding G to each consecutive term (intersections with lines formed by
tangents add each point to themself and have no knowledge of the value of
some arbitrary G which for a specific instance such that it doesnt depend
on notation).  Basically, the sequence should go G, 2G, 4G, 8G, 16G, etc
instead of G, 2G, 3G, 4G, 5G because adding subsequent terms (such as 2G)
with themself would not have knowledge of a specific random previous value
(such that 2G + 2G = 3G as shown) and be consistent - what if a world
existed where I chose 2G = H, then H+H = 3G which makes little sense.

Specifically, to descirbe the corrected graph the following changes should
be made:
3G -> 4G
4G -> 8G
5G -> 16G

Also, I would think it would be advantageous to tell andreas that having an
additional graph showing addition of two points (not being the same)
through the process of drawing a line through them and finding the graphs
3rd intersection point (if it exists) would be very helpful.

I know this is in the later chapters which have been authored  by him which
I suspect have not been as reviewed as the previous ones, however I feel
this is something that must be corrected based on fundamentals as it is
either very misleading or incorrect.  Im sure he will recognize the error
(or possibly further clarify any misinterpretations), as I have been paying
attention to him for about 6 months now as he has become a public icon in
the bitcoin community.

Thank you

On Sun, Jun 1, 2014 at 6:27 PM, Minh T. Nguyen notifications@github.com
wrote:

> I don't understand the math behind this, so will assign to Andreas for
> commenting.
> 
> Scott -- would you also mind describing the exact expected vs. actual
> graphic? What would you have expected the graphic to be like?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aantonop/bitcoinbook/issues/34#issuecomment-44792691.

## 

Scott Bannert

Cell: (979) 418-2422

**Comment by aantonop** [comment]
Excellent point,  you are correct. I will correct it ASAP.  I will also add
a point addition chart as you suggested

**Comment by bannerts** [comment]
I've attached some pages from a reference that I think does a good job
describing the details discussed above.  I think referencing this resource
as much as possible and using a similar graphic would be ideal as they do a
really good job which I see no need for improvement.

**Comment by aantonop** [comment]
Fixed
