### ISSUE TITLE
Incorrect value in Transaction chains (ch02.asciidoc)

### ISSUE THREAD

**Issue by ankit-maverick** [bitcoinbook/bitcoinbook#340]
In https://github.com/bitcoinbook/bitcoinbook/blob/second_edition/images/mbc2_0204.png
Output # 1 Bob's Address(change) should be 0.0045BTC (unspent) instead of 0.0845BTC

**Comment by aantonop** [comment]
Fixed in second print

**Comment by ankit-maverick** [comment]
@aantonop :+1
