### ISSUE TITLE
' character not showing correctly in chapter 5

### ISSUE THREAD

**Issue by KanoczTomas** [bitcoinbook/bitcoinbook#341]
In section named "Navigating the HD wallet tree structure" there are several cases where the ' character is displayed as & #x27; There are sentences where the character is displayed once correctly, once in html code of the character. e.g.:

Bitcoin is m/44'/0', Bitcoin Testnet is m/44& #x27;/1& #x27;, and Litecoin is m/44& #x27;/2& #x27;.

Checked on several browsers and platforms, all web browsers show the same "mistake".

**Comment by KanoczTomas** [comment]
note i had to update the comment as it was correctly decoding the characters here on github, so added an extra space after "&" so the browser would not change it to '.

**Comment by KanoczTomas** [comment]
pull request #342

**Comment by aantonop** [comment]
The character is rendered correctly by the build system used by O'Reilly Media, for the PDF and HTML/ebook versions. Therefore, we cannot change it here as that would break it in the paperback

**Comment by KanoczTomas** [comment]
ok I understand, but still just want to make sure my point was clear - as am not a native english speaker ... the text corrected has both the html code and the ' character itself, so the build system must be able to handle both probably, but the browsers not. So changing the ' character to its non html format should not break the build system - or should it? Am not familiar with the build system, so please take it as a constructive question of a noob and not a critique of any kind :) 
TY
