### ISSUE TITLE
Confusing example "Simplified Proof-Of-Work Implementation"

### ISSUE THREAD

**Issue by chiro-hiro** [bitcoinbook/bitcoinbook#353]
I have read this section
>  Example 8-11. Simplified Proof-Of-Work Implementation

This example isn't bitcoin proof of work, in fact that's an example to learn about mining process, isn't it?

**Comment by wbnns** [comment]
@tad88dev Hello, yes, this is a basic example providing insight into PoW (proof of work) which is part of the mining process.
