### ISSUE TITLE
Confusing nSequence power of two's typos in "Original meaning of nSequence"

### ISSUE THREAD

**Issue by RIscRIpt** [bitcoinbook/bitcoinbook#354]
In chapter "[Original meaning of nSequence](https://github.com/bitcoinbook/bitcoinbook/blob/second_edition/ch07.asciidoc#original-meaning-of-nsequence)" there are mentioned following power of two's numbers:

> 2**32 (0xFFFFFFFF)

and

> 2**32 – 1 (0xFFFFFFFE)

I think there are off-by-one mistakes/typos, because

`2**32 = 0xFFFFFFFF + 1 = 0x100000000`, and
`2**32 - 1 = 0xFFFFFFFF`

As I'm only learning bitcoin I'm not sure what are correct values (decimal or hexadecimal) there (and I'm currently very confused 😕).
But assuming that nSequence number is 32bit, it should be changed as follows:

> 2**32 – 1 (0xFFFFFFFF)

and

> 2**32 – 2 (0xFFFFFFFE)

I think @edposnak can address this issue, because this text was added by his pull-request #237 (nSequence discussion).

**Comment by edposnak** [comment]
Thanks @RIscRIpt. You are correct. In PR https://github.com/bitcoinbook/bitcoinbook/pull/237 I just copied the original values that were in the text, but they should be as you say. I will create another PR to capture this input.

**Comment by edposnak** [comment]
@RIscRIpt I think PR https://github.com/bitcoinbook/bitcoinbook/pull/356 fixes all the inconsistency issues. Please let me know if anything still looks confusing. 

For reference on the values that I changed, see https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki

**Comment by ridzenis** [comment]
Thanks @edposnak, it makes sense now.
Although the part "less than 2**31" wasn't that obvious, I'd write it like "less or equals to 0x7FFFFFFF", but it doesn't really matter.

As for the issue, I guess it should stay open while PR is not accepted.

**Comment by edposnak** [comment]
Cool. Thanks @RIscRIpt for reviewing the PR. I elected to stick with 2^31^ to be
consistent with the following section that explains in more detail how the
disable bit is used in relative time locks.
