### ISSUE TITLE
Chapter 2: Figure 4 : 3rd Transaction

### ISSUE THREAD

**Issue by AhmedKamal20** [bitcoinbook/bitcoinbook#360]
[Chapter 2](https://github.com/bitcoinbook/bitcoinbook/blob/second_edition/ch02.asciidoc)

![image](https://user-images.githubusercontent.com/14352372/29229187-5287384e-7edd-11e7-9083-ad7f30806ed8.png)

How is the two outputs of the third transaction are `unspent` ? , and they didn't add up to the input

**Comment by wisdomworker** [comment]
Once, second output of the third transaction is not to be 0.0845BTC, but 0.0045BTC. I created PR for fixing right now. unspent transaction outputs can be spent as an input in a new transaction, so those are unspent.

**Comment by wbnns** [comment]
Thank you both! Fixed in `0e9ba5e`. 👍
