### ISSUE TITLE
Is figure 10 in chapter 5 correct ?

### ISSUE THREAD

**Issue by hss14** [bitcoinbook/bitcoinbook#365]
I'm confused about the Figure 10 of chapter 5. 
It's basically the same as Figure 9 of chapter 5, and it doesn't illustrate the purpose described by its caption. 

fig.0509: Creating master keys and (master) chain code from a root seed
![fig.0509](https://github.com/bitcoinbook/bitcoinbook/blob/second_edition/images/mbc2_0509.png)

fig.0510: Extending a parent private key to create a child private key
![fig.0510](https://github.com/bitcoinbook/bitcoinbook/blob/second_edition/images/mbc2_0510.png)

**Comment by hss14** [comment]
I found the first edition of mastering bitcoin and located the corresponding section( Figure 4-11 on page 91, in section 4.3.4 Hierarchical Deterministic Wallets ).

Now I'm pretty sure Figure 0510 is mistaken. Hope it can be corrected soon.

**Comment by wbnns** [comment]
@hss14 Hello, nice catch - thanks for mentioning. Will fix. 👍

**Comment by wbnns** [comment]
@hss14 This is updated in the `develop` branch, which will ensure that it gets incorporated into a future edition.
