### ISSUE TITLE
How do you compile this to pdf or word?

### ISSUE THREAD

**Issue by PedroD** [bitcoinbook/bitcoinbook#369]
Hello.

How can I compile all this source code to a pdf or a word file?

Thanks

**Comment by varunudacity** [comment]
See this: 
https://github.com/bitcoinbook/bitcoinbook/issues/196
There one of the responses suggest using a2x 

However it doesn't render perfectly, so I suspect something is missing.

**Comment by hograthm** [comment]
The proper way to compile the book is [O'Reilly Atlas](https://atlas.oreilly.com/). We probably should ask maintainer to compile it because ordinary users can't access Atlas platform.

**Comment by varunudacity** [comment]
Is there a way to simulate what Atlas does?

**Comment by wbnns** [comment]
@PedroD 

Hello, currently, the second edition isn't available in PDF or Doc format, however, if you're interested in a digital copy, I'd recommend the Kindle eBook format currently available on Amazon:
https://www.amazon.com/Mastering-Bitcoin-Programming-Open-Blockchain-ebook/dp/B071K7FCD4/ref=mt_kindle?_encoding=UTF8&me=

Not only does it save trees, it supports Andreas as well, along with his future efforts. 👍
