### ISSUE TITLE
Alert Messages (first edition), chapter 6

### ISSUE THREAD

**Issue by ThomasZimmermann** [bitcoinbook/bitcoinbook#374]
Apologies, a bit late to the party, I understand that the alert system was retired in 2016, but in Chapter 6 of the first edition of the book it says:

"Alerts are cryptographically signed by a public key. The corresponding private key is held by a few select members of the core development team. The digital signature ensures that fake alerts will not be propagated on the network."

Weren't the alerts signed by the private key held by the few select members and the public key was used to verify the signature?

**Comment by aantonop** [comment]
Not making changes to the first edition
