### ISSUE TITLE
having a hard time compiling cpp code examples

### ISSUE THREAD

**Issue by jcramer** [bitcoinbook/bitcoinbook#378]
I apologize if this is the wrong place to post my troubles.  I've installed libbitcoin am now getting errors I cannot solve during compilation of addr.cpp adn other cpp files.  There are a bunch of depreciation warnings which are followed by the error.  Here's one warning with the errors I'm getting:
```
In file included from /usr/include/boost/iostreams/detail/is_dereferenceable.hpp:13:0,
                 from /usr/include/boost/iostreams/detail/resolve.hpp:26,
                 from /usr/include/boost/iostreams/detail/push.hpp:24,
                 from /usr/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31,
                 from /usr/include/boost/iostreams/stream_buffer.hpp:22,
                 from /usr/include/boost/iostreams/stream.hpp:21,
                 from /usr/local/include/bitcoin/bitcoin/utility/container_sink.hpp:24,
                 from /usr/local/include/bitcoin/bitcoin/message/messages.hpp:57,
                 from /usr/local/include/bitcoin/bitcoin.hpp:114,
                 from addr.cpp:1:
/usr/include/boost/type_traits/detail/template_arity_spec.hpp:13:84: note: #pragma message: NOTE: Use of this header (template_arity_spec.hpp) is deprecated
 # pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
                                                                                    ^
addr.cpp: In function ‘int main()’:
addr.cpp:12:5: error: ‘ec_point’ is not a member of ‘bc’
     bc::ec_point public_key = bc::secret_to_public_key(secret);
     ^~
addr.cpp:13:36: error: ‘encode_hex’ is not a member of ‘bc’
     std::cout << "Public key: " << bc::encode_hex(public_key) << std::endl;
                                    ^~
addr.cpp:13:51: error: ‘public_key’ was not declared in this scope
     std::cout << "Public key: " << bc::encode_hex(public_key) << std::endl;
                                                   ^~~~~~~~~~
```

From the warning message, it looks like the compiler can see bitcoin.hpp file, but for some reason the namespace 'bc' doesn't have the methods `ec_point` etc?  I'm not a pro in c++ so this is probably user error rather than a bug.

Using Ubuntu 16.10 with g++ compiler version 6.2.0

**Comment by ipaxos** [comment]
Im having the same issue with libbitcoin and addr.cpp but on unix.

The command `g++ -std=c++11 -o addr addr.cpp $(pkg-config --cflags --libs libbitcoin)`

The errors

```
addr.cpp:11:9: error: no type named 'ec_point' in namespace 'libbitcoin'
    bc::ec_point public_key = bc::secret_to_public_key(secret);
    ~~~~^
addr.cpp:11:35: error: no member named 'secret_to_public_key' in namespace 'libbitcoin'
    bc::ec_point public_key = bc::secret_to_public_key(secret);
                              ~~~~^
addr.cpp:12:40: error: no member named 'encode_hex' in namespace 'libbitcoin'; did you
      mean 'encode_hash'?
    std::cout << "Public key: " << bc::encode_hex(public_key) << std::endl;
                                   ~~~~^~~~~~~~~~
                                       encode_hash
/usr/local/include/bitcoin/bitcoin/formats/base_16.hpp:65:20: note: 'encode_hash'
      declared here
BC_API std::string encode_hash(hash_digest hash);
                   ^
3 errors generated.
```

**Comment by jcramer** [comment]
No progress. I even tried it a second time over weekend on a fresh Ubuntu 16.04 image and got the same result.

Seems to me like some breaking changes were made in libbitcoin.  I didn't research in their github change logs.

**Comment by amanusk** [comment]
It seems most of these issues have been resolved in the [develop](https://github.com/bitcoinbook/bitcoinbook/tree/develop) branch of this repository.

**Comment by jcramer** [comment]
@amanusk Thanks for pointing me to that.

**Comment by icecoldlilly** [comment]
You can achieve the correct result using the latest installation of libbitcoin and the c++11 flag w/ g++ as following:
`g++ -std=c++11 -o addr addr.cpp $(pkg-config --cflags --libs libbitcoin)`

**Comment by mddia** [comment]
I am having a similar problem with libbitcoin on ubuntu 16.

 error: ‘block_type’ was not declared in this scope     

in this code:
#include <bitcoin/bitcoin.hpp>
using namespace bc;

int main()
{
    block_type blk = genesis_block();
    std::cout << encode_hex(hash_block_header(blk.header)) << std::endl;
    return 0;
}
