### ISSUE TITLE
Chapter 4: Generating Vanity Addresses

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#38]
First paragraph, last sentence:  "There are approximately 58^31...."

Shouldn't that be approximately 58^29 ?
There are 29 symbols after "1Kids" in "1Kids11111111111111111111111111111".

**Comment by enderminh** [comment]
Nice catch. :+1: 

I fixed it with commit b4468d0aa993dd76e2db64e7f91cf9e8bc95e18b
