### ISSUE TITLE
Issue with example 4-4 using libbitcoin with MacOSX High Sierra Unix

### ISSUE THREAD

**Issue by ipaxos** [bitcoinbook/bitcoinbook#380]
I am having issues trying to run the addr.cpp program

I enter the command `g++ -std=c++11 -o addr addr.cpp $(pkg-config --cflags --libs libbitcoin)`
and then get these errors
```
addr.cpp:11:9: error: no type named 'ec_point' in namespace 'libbitcoin'
    bc::ec_point public_key = bc::secret_to_public_key(secret);
    ~~~~^
addr.cpp:11:35: error: no member named 'secret_to_public_key' in namespace 'libbitcoin'
    bc::ec_point public_key = bc::secret_to_public_key(secret);
                              ~~~~^
addr.cpp:12:40: error: no member named 'encode_hex' in namespace 'libbitcoin'; did you
      mean 'encode_hash'?
    std::cout << "Public key: " << bc::encode_hex(public_key) << std::endl;
                                   ~~~~^~~~~~~~~~
                                       encode_hash
/usr/local/include/bitcoin/bitcoin/formats/base_16.hpp:65:20: note: 'encode_hash'
      declared here
BC_API std::string encode_hash(hash_digest hash);
                   ^
3 errors generated.
```

Can someone please help me?

**Comment by pmienk** [comment]
Without a deep dive into this, it looks as though these examples apply to an older version of libbitcoin than the current master.  Does this example reference the version and have you tried that one?  I recognize that bc::secret_to_public_key existed in version2 but is not currently in master, if that helps.  I did not look exhaustively.

**Comment by ipaxos** [comment]
No there is not a reference for the specific version. Thank you for the help, I think that is the problem

**Comment by jcramer** [comment]
also, check out the `develop` branch of this repo, where some of libbitcoin V3 issues have been resolved

**Comment by nealwright** [comment]
In case this helps anyone, I used version v2.12.0 of libbitcoin and it worked with the code example from chapter 4.

**Comment by icecoldlilly** [comment]
Use the latest code, and install libbitcoin from brew

**Comment by xgess** [comment]
also on a mac running libbitcoin 3.4.0 and seeing the same errors. i was able to get it to work by tweaking the sample code to match the existing APIs of libbitcoin. 
replacing these two lines (11 and 12)
```cpp
bc::ec_point public_key = bc::secret_to_public_key(secret);
std::cout << "Public key: " << bc::encode_hex(public_key) << std::endl;
```
with these three lines
```cpp
bc::ec_compressed public_key;
bc::secret_to_public(public_key, secret);
std::cout << "Public key: " << bc::encode_base16(public_key) << std::endl;
```
does the trick.

**Comment by be1ay** [comment]
My code:
#include <bitcoin/bitcoin.hpp>
#include <iostream>

int main() {
bc::ec_secret secret;
bc::decode_base16(secret,"038109007313a5807b2eccc082c8c3fbb988a973cacf1a7df9ce725c31b14776");
bc::ec_compressed public_key;
bc::secret_to_public(public_key, secret);    // this function not working
std::cout << "Public key: " << bc::encode_base16(public_key) << std::endl;
}
But its not working...
Errors:

/home/aleks/libbitcon/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_mod_inverse':
/home/aleks/build-libbitcoin/secp256k1/src/num_gmp_impl.h:128: undefined reference to `__gmpn_gcdext'
/home/aleks/libbitcon/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `__gmpn_sub':
/usr/include/x86_64-linux-gnu/gmp.h:2194: undefined reference to `__gmpn_sub_n'
/home/aleks/libbitcon/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_set_bin':
/home/aleks/build-libbitcoin/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
/home/aleks/build-libbitcoin/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
/home/aleks/build-libbitcoin/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
/home/aleks/libbitcon/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_get_bin':
/home/aleks/build-libbitcoin/secp256k1/src/num_gmp_impl.h:34: undefined reference to `__gmpn_get_str'
/home/aleks/build-libbitcoin/secp256k1/src/num_gmp_impl.h:34: undefined reference to `__gmpn_get_str'
collect2: error: ld returned 1 exit status
