### ISSUE TITLE
Chapter 6 - "Sender adress" in transaction data

### ISSUE THREAD

**Issue by weinim** [bitcoinbook/bitcoinbook#382]
Chapter 6, underneath figure 6-7: 

> On the left side of the transaction, the blockchain explorer shows Alice’s bitcoin address as the "sender." In fact, this information is not in the transaction itself. When the blockchain explorer retrieved the transaction it also retrieved the previous transaction referenced in the input and extracted the first output from that older transaction.

Is it really necessary to retriev the previous transaction? 
In my understanding, the scriptSig contains the "sender´s" public key (PubK). Transforming this PubK to a Bitcoin address leads to the expected result.

With libbitcoin explorer the following command
`bx ec-to-address 0484ecc0d46f1918b30928fa0e4ed99f16a0fb4fde0735e7ade8416ab9fe423cc5412336376789d172787ec3457eee41c04f4938de5cc17b4a10fa336a8d752adf`

gives the result

`1Cdid9KFAaatwczBwBttQcwXYCpvK8h7FK`

This is the "sender´s" address as it is displayed in figure 6-7.

**Comment by wbnns** [comment]
@weinim Thank you; resolved w/ 70138ae.
