### ISSUE TITLE
On-disk size of blockchain

### ISSUE THREAD

**Issue by johnfrombluff** [bitcoinbook/bitcoinbook#386]
In Chapter 8, you've written that the size of the bitcoin blockchain data on disk is about 20+ GB. This is way out of date, perhaps it's a simple typo for 120+?

But it might simply be better to say that it's size X at the time of writing, but growing fairly linearly at Y%, and link to an online service, e.g. [https://blockchain.info/charts/blocks-size](https://blockchain.info/charts/blocks-size)

Thanks for the great book, Andreas, and thanks to O'Reilly for making it available gratis!

**Comment by aantonop** [comment]
Thanks fixed 3cff672
