### ISSUE TITLE
Image too small in print version of the second edition

### ISSUE THREAD

**Issue by Hermetic** [bitcoinbook/bitcoinbook#401]
In the print version of the 2nd edition the image **_Figure 1. Bitcoin overview_** (mbc2_0201.png) is too small to be legible.  It should perhaps be turned on its side and take up a whole page.

Still reading so not sure yet if there are other images that are similarly too small.

**Comment by aantonop** [comment]
Don't have the original source any more. I'll have to replace this image entirely. Moved to third-edition milestone

**Comment by wbnns** [comment]
Just wanted to leave a note that this does not appear to be as significant of an issue in digital / electronic editions of the book since it is possible to zoom in.
