### ISSUE TITLE
[First Edition - Chapter 9] Mastercoin ticker is wrong

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinbook/bitcoinbook#402]
Hello,

On chapter 9 of the first edition, paragraph about Mastercoin, the ticker is wrong. https://github.com/bitcoinbook/bitcoinbook/blob/first_edition/ch09.asciidoc#mastercoin
It is not MST but MSC.

MST has existed but was an uninteresting coin (https://bitcointalk.org/index.php?topic=242406.0).
The right BitcoinTalk page is: https://bitcointalk.org/index.php?topic=265488.0

**Comment by aantonop** [comment]
First Edition is not being developed further
