### ISSUE TITLE
Section 12.6.4 - Clarify revokation key properties

### ISSUE THREAD

**Issue by nonsequitur** [bitcoinbook/bitcoinbook#406]
The way commitment revokation is described, it seems as if the `revocation public key` were an ordinary public key to which the private key is published on revokation. But then the publishing party would still be able to spend the penalty output, as it still owns the key.
Of course, the revokation key is [designed](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#revocationkey-derivation) similarly to a 2-of-2 multisig key, where one party can assign full control over the key to the other party by disclosing the private key.
This should be mentioned somewhere.

**Comment by aantonop** [comment]
Clarified the nature of revocation keys. bitcoinbook@e93a8c42b0380fd788581fd97b86518d7d976a82 and bitcoinbook@5b035b14dbcfc2aca4959276c917025f55ee13f1
