### ISSUE TITLE
Equations are not rendered correctly

### ISSUE THREAD

**Issue by someone235** [bitcoinbook/bitcoinbook#408]
In chapter 4 equations look like this:
\[\begin{equation} {y^2 = (x^3 + 7)}~\text{over}~(\mathbb{F}_p) \end{equation}\]

I tried to compile the book to epub and xhtml, but it didn't help, and the equations were still malformed.
Is there a way to solve this?

**Comment by aantonop** [comment]
O'Reilly's rendering engine supports latexmath, which is what this is. It does not render in GitHub, but it does on the O'Reilly paperback and ebook.
