### ISSUE TITLE
Rename this book to 'Bitcoin Core Book'.

### ISSUE THREAD

**Issue by jli225** [bitcoinbook/bitcoinbook#413]
Hi Mr. Will Binns, thanks for you spending time on this book. I really appreciate it.

However, let's keep honest and rename the new version of this book to 'Bitcoin Core Book'. 

Since you are one important person who is helping the Bitcoin Core chain to fight against the real Bitcoin chain. So it's immoral to intentionally cause confusion among newbies by pretending that you are still working for Bitcoin.

You can do anything on your Bitcoin Core chain, Knots or not, censorship or not. We Bitcoiners don't care. But at least please don't maliciously mislead newbies out of evil will.

I really appreciate it if you can be honest on this issue in the future. You will still be a good person, who works for the enemy of Bitcoin.

**Comment by pezcore** [comment]
No. This book in it's current form is about Bitcoin as it existed at the time of writing. All topics included *are* bitcoin.

**Comment by jli225** [comment]
@pezcore This book mentioned the infamous segwit, so it's certainly about BitcoinCore Coin or SegWit Coin, instead of Bitcoin. Please keep honest on this issue.

Don't defame Bitcoin in this way, please.

**Comment by rpm604** [comment]
@jli225 lol, you're embarrassing yourself. Go away.

**Comment by mihael** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/407
https://github.com/bitcoinbook/bitcoinbook/issues/427

`helping the Bitcoin Core chain to fight against the real Bitcoin chain. ` ???

I am not aware of any fights going on. Forks have their own chains. A forked chain is no longer "connected" to the original chain, it can not win it over in any way possible. 

It is so hard to understand @jli225 issues/pulls and what the motivation behind these is. Seems either personal, or some kind of trolling. 

Cheers

P.S. 

Why not rather fork and rename the forked book. ;)

**Comment by jli225** [comment]
@mihael So what's the name of the forked coin? Bitcoin Core coin? Or you prefer 'SegWit Coin'? Have you already realized "a forked coin is no longer 'connected' to the original chain"? So can you answer your own question --- 'Why not rather fork and rename the forked' coin?


It's hard to keep both core and logic at the same time. However, if you have to resort to double standard and lies, if your own arguments are self-contradictory, if your mates wield censorship to achieve censorship-resistance, you should at least realize that you are standing on the wrong side.


I wholeheartedly support anyone's freedom to support Segwit Coin, and I would even defend your right to call it 'Bitcoin', although it's a common sense that the Segwit coin contradicts to everything Bitcoin stands for. Anyway, It's your freedom. But, intentionally causing unnecessary user confusion between Bitcoin and Segwit coin will mislead them to buy fake bitcoins thus will result in the loss of their hard-earned money. So it's not only immoral but also potentially illegal. 


If the aim of this book is to spread knowledge, the first rule should always be 'not misinform people maliciously'. Don't degenerate into another bitcoin.org.

Never do evil. 

Please.

**Comment by fogoat** [comment]
BTC to me is the one and only Bitcoin.

Are these people BCH trolls? Thanks Roger Ver (Boo). I'm gonna call your coin bcash if you trolls keep harassing people.

**Comment by ch4bes** [comment]
“Don't degenerate into another bitcoin.org.”

Trolls will troll. I think this “issue” can be closed now..

**Comment by montvid** [comment]
So far i was reading Alice was buying coffee with bitcoin in Chapter 2 so it is a bitcoin cash book for sure. Nowhere it is written that Alice has to enable Replace by Fee just in case her tx does not get confirmed for the coffee OR do a Child pays Parent OR pay a miner service to make her tx unstuck. Only someone haven't read the book can say it is about bitcoin core. :smiley_cat:
