### ISSUE TITLE
Confusing / Inaccurate statement in "Successfully Mining the Block" section

### ISSUE THREAD

**Issue by thiccar** [bitcoinbook/bitcoinbook#414]
Relevant section below (emphasis mine):

> Next, the mining node running on Jing’s desktop transmits the block header to his mining hardware, which starts testing **trillions** of nonces per second.
> 
> Almost **11 minutes** after starting to mine block 277,316, one of the hardware mining machines finds a solution and sends it back to the mining node. When inserted into the block header, the nonce **4,215,469,401** produces a block hash of [...]

How can it take 11 minutes of testing trillions of nonces per second to reach the nonce value of just over 4 billion?  From the numbers, it should have taken less than a second.

**Comment by aantonop** [comment]
Explained use of extra nonce and timestamp in header, to exceed 4 billion combinations

bitcoinbook@801374b344966c32185d9dcae7ddb31814968dfa
