### ISSUE TITLE
Confusing discussion of random number generation

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#417]
The note about `ec_math` says:

> ec_math uses +os.urandom+, which reflects a cryptographically secure random number generator (CSRNG) provided by the underlying operating system…While the random number generator used here is for demonstration purposes, it is _not_ appropriate for generating production-quality bitcoin keys as it is not implemented with sufficient security.

One minor problem: "is for demonstration purposes" should be "is suitable for demonstration purposes".

Bigger problem: there's confusion between saying that a CSRNG is used, and then saying "it is not appropriate for generating production-quality bitcoin keys". Presumably what the text is trying to say is that depending on one's OS, `ec_math` may not be using a CSRNG? In that case, it would be better to say something like: "Since in some cases `ec_math` may not be able to use a CSRNG, it is not appropriate for generating production-quality bitcoin keys".

**Comment by aantonop** [comment]
Clarified in bitcoinbook@ff996795f9d6b5c9aebc83e7671e8cade6a57afc
