### ISSUE TITLE
"Alternate stack" mentioned before it is introduced

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#418]
In chapter 6, there's a reference "(not the alternate stack)", but at this point the alternate stack has not been introduced, so either it should be, or a forward reference is needed!

**Comment by aantonop** [comment]
Removed mention of alternate stack. It's not important in this context, adds confusion unnecessarily 
bitcoinbook@6e20da5e14982b89eb573275f87d7b8807723d86
