### ISSUE TITLE
ECDSA: don't put readers off!

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#419]
The book says "The math of ECDSA is complex and difficult to understand." This is a shame, there's enough "math is difficult" propaganda out there. Also, the math is not complex (it's basically arithmetic); the organisation is just rather involved. How about something like:

ECDSA is necessarily a fairly complicated piece of machinery; a full explanation is beyond the scope of this book. A number of great guides online take you through it step by step: search for "ECDSA explained" or try this one: http://bit.ly/2r0HhGB[].

**Comment by aantonop** [comment]
MATH ISN'T SCARY ANY MORE!  :tada: 
bitcoinbook@53c74797f18ab57042f07a85def467a0b57db304
