### ISSUE TITLE
Minor hole in explanation of CLTV

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#421]
The text says: "is now impossible for either Bob or Alice to spend it before the 3-month locktime has expired."

This raises the question: does that mean that there's still a problem when the locktime expires, that Alice could very quickly spend the money before Bob gets around to it? Answer: no! But it's not clear from the wording above. How about something like:

"Alice can no longer spend the money (because it's locked with Bob's key) and Bob cannot spend it before the 3-month locktime has expired."

**Comment by aantonop** [comment]
Fixed bitcoinbook@9c783e1edf6c8773d4d7f41a9aa3f8a02c7403a6
