### ISSUE TITLE
Confusing explanation of operation of bitcoin core on testnet

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#423]
The text (Chapter 9) says: "Bitcoin Core, like almost all other bitcoin software, has full support for operation on testnet instead of mainnet, but also allows you to mine testnet coins and operate a full testnet node."

It's not clear what the differenec is between "full support for operation on testnet" and "allows you to operate a full testnet node" is (note the "but"). I'm not entirely clearly what is meant here: is it saying that bitcoind can simultaneously operate on mainnet and testnet? If not, I don't see what difference is being explained.

**Comment by aantonop** [comment]
Fixed bitcoinbook@fe0e7f6059e7459ff170fb022481a459c268e224
