### ISSUE TITLE
Ch 4 - Compressed Public Keys

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#43]
Second paragraph, last sentence:
"A 50% reduction in size in every transaction adds up to a lot of data saved over time!"
I would suggest changing that to something like: "An almost 50% reduction in size..."

Because the public key is 520 bits when uncompressed and 264 when compressed - which is about 50.77% of the uncompressed key.

**Comment by enderminh** [comment]
Done.
