### ISSUE TITLE
Html entities are not displayed correctly in chapter 6

### ISSUE THREAD

**Issue by someone235** [bitcoinbook/bitcoinbook#433]
In chapter 6,  the sentence: "Transactions are valid if the top result on the stack is TRUE (noted as \&#x7b;0x01\&#x7d;)" Should be fixed to "Transactions are valid if the top result on the stack is TRUE (noted as &#x7b;0x01&#x7d;)". Same mistake happens again in this sentence: "a zero-length empty value, noted as \&#x7b;\&#x7d;"

**Comment by nothingmuch** [comment]
~Related: 53e1e8f8fc6880b323a152604bf2bef7b891dd93~
Related: 72876dc7c6892a722236b4a62927455956b2726d [great commit messages, Atlas code editor =P]
