### ISSUE TITLE
Appendix D (SegWit) confusion around SegWit P2SH address generation.

### ISSUE THREAD

**Issue by grisha** [bitcoinbook/bitcoinbook#440]
Right above `3deadbeef` (fixed in issue #331) there is also a confusing (if not erroneous) part:

<blockquote>
The hash of the witness program is then embedded in a P2SH script:

```
HASH160 3e0547268b3b19288b3adef9719ec8659f4b2b0b EQUAL
```
Finally, the P2SH script is converted to a P2SH bitcoin address:

```
37Lx99uaGn5avKBxiW26HjedQE3LrDCZru
```
</blockquote>

This reads to me like `HASH160 3e0547268b3b19288b3adef9719ec8659f4b2b0b EQUAL` somehow becomes `37Lx99uaGn5avKBxiW26HjedQE3LrDCZru`, but actually, the address is derived from the *witness program* mentioned three paragraphs earlier (`0 ab68025513c3dbd2f7b92a94e0581f5d50f654e7`):

```sh
echo '0 [ab68025513c3dbd2f7b92a94e0581f5d50f654e7]' | bx script-to-address 
37Lx99uaGn5avKBxiW26HjedQE3LrDCZru
```

A similar problem down below (bottom of page 339 in print):

<blockquote>

Mohammed’s wallet creates a P2WSH witness program
```
0 9592d601848d04b172905e0ddb0adde59f1590f1e553ffc81ddc4b0ed927dd73
```
Then, the witness program itself is hashed with SHA256 and RIPEMD160, producing a new 20-byte hash, as used in traditional P2SH:
```
  86762607e8fe87c0c37740cddee880988b9455b2
```
Next, Mohammed’s wallet puts the hash into a P2SH script:
```
  HASH160 86762607e8fe87c0c37740cddee880988b9455b2 EQUAL
```
Finally, the wallet constructs a bitcoin address from this script:
```
3Dwz1MXhM6EfFoJChHCxh1jWHb8GQqRenG
```
</blockquote>

The wallet constructs the address not from "this script", but rather from the witness program:
```sh
echo '0 [9592d601848d04b172905e0ddb0adde59f1590f1e553ffc81ddc4b0ed927dd73]' | bx script-to-address 
3Dwz1MXhM6EfFoJChHCxh1jWHb8GQqRenG
```

P.S. Fantastic book, BTW, thank you!

**Comment by aantonop** [comment]
Confirming...

**Comment by aantonop** [comment]
Thank you for this. You found several errors. I had mixed up the steps. 

Now fixed, with bx examples throughout and correct addresses bitcoinbook/bitcoinbook@1ddd89b65841dea02b5c4ab1e31cf1f4de23ba52

Please review and confirm, if you can!
