### ISSUE TITLE
Wrong output value in bitcoinbook/images/mbc2_0204.png 

### ISSUE THREAD

**Issue by mhzgh** [bitcoinbook/bitcoinbook#446]
Transaction 3: Bob sends to Gopesh

Input has 0.015, but outputs are displayed as 0.0100 + 0.0845 + 0.0005.
Bobs "change" should be 0.0045, right? :-)

**Comment by montvid** [comment]
Fixed in dev branch, please see https://github.com/bitcoinbook/bitcoinbook/blob/develop/images/mbc2_0204.png

I can't seem to find the tx id in Block Explorer for the tx of 0.01 to Gopesh - can you? Why mix real and imaginary tx is beyond me.

**Comment by mhzgh** [comment]
Great, thanks!

Me neither - but I have to admit I didn't check on that while reading.

**Comment by montvid** [comment]
You're welcome! I read the dev branch of the book.
Sadly I asked about Gopesh txid but I was ignored by the author see closed #468

**Comment by aantonop** [comment]
Already fixed, thanks
