### ISSUE TITLE
Code produces wrong address in addr.cpp

### ISSUE THREAD

**Issue by 30mb1** [bitcoinbook/bitcoinbook#449]
```
// Private secret key string as base16
bc::ec_secret decoded;
bc::decode_base16(decoded,
        "038109007313a5807b2eccc082c8c3fbb988a973cacf1a7df9ce725c31b14776");

bc::wallet::ec_private secret(
decoded, bc::wallet::ec_private::mainnet_p2kh);

// Get public key.
bc::wallet::ec_public public_key(secret);
std::cout << "Public key: " << public_key.encoded() << std::endl;
```
This creates compressed public key and further conversions create an invalid address.

Code result addr: 1PRTTaJesdNovgne6Ehcdu1fpEdX7913CK
Correct one: 14K1y4Epb341duzDmWsPniLyBh9EVh8jG3

**Comment by pavlovdog** [comment]
Whoa, looks like a pretty serious misprint. @30mb1, what tool have you used to get the "Correct one" address?

**Comment by 30mb1** [comment]
@pavlovdog You can use [this tool](http://gobittest.appspot.com/Address) to check every step of creating address from the private key.

**Comment by aantonop** [comment]
The example uses a _compressed_ public key, which correctly results in the address 1PRTT... The web tool you used, produced an uncompressed public key which produces a different address 14K1y... Both are correct, just different methods for the public key. I moved the example down to the section after compressed public keys and added a TIP to clarify this issue. 

Use bitaddress.org "Wallet Details" to see both compressed and uncompressed public keys and the two different addresses they produce. Now go back and see if you can spot the difference between the addr.cpp code public key and the one produced by TP's web site.

bitcoinbook@69c00abc345019e2e8941ad8032724231cee3a04

**Comment by 30mb1** [comment]
@aantonop Thank you for response! Will you provide code for creating uncompressed public keys? I didn't find appropriate method.
