### ISSUE TITLE
Ch. 10: "hardier, stealthier, and more robust"

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#450]
There's no obvious difference between Bitcoin being "hardy" and its being "robust'. Perhaps delete "hardier"? (Normally "hardy" is used of people and animals, not things, as it pertains to active endurance.)

Also, it's unclear in what sense Bitcoin is "stealthy", and in what sense countermeasures to consensus attacks would make it "stealthier". Perhaps just remove this word? If not, explain it?

**Comment by aantonop** [comment]
Fixed bitcoinbook@93645d1a5b0e0013924ba41d0e0546dc73e8898b
