### ISSUE TITLE
Ch. 10: "REJECTED" or "FAILED"?

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#452]
The text says: "If the timeout is elapsed before the voting threshold has been reached, the proposal state changes to +FAILED+, indicating a rejected proposal. +REJECTED+ proposals remain in that state perpetually."

Presumably "FAILED" should be "REJECTED", or vice versa.

Also, "If the timeout is elapsed" should be "If the timeout elapses".

**Comment by iRoark** [comment]
Please remove me.  I’ve unsubscribed 3 times but still getting this stuff. Please.

**Comment by aantonop** [comment]
Fixed bitcoinbook@e319186321b9afe10403e122610150205b61edf7
