### ISSUE TITLE
Several occurrences: prefer "just as" to "just like" when used adverbially

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#454]
In chapters 6 and 12, and in the glossary, "just like" is used adverbially. Many readers will find this confusing, as "just like" is more often used adjectivally. I found myself having to re-parse sentences half-way through when I realised the initial clause was adverbial.

I suggest using "just as" in these cases.

There are other, adjectival, uses of "just like", which are fine (in chapters 7 and 9).

**Comment by aantonop** [comment]
I'm not sure I can tell the difference. Should've paid more attention in English grammar class. Oh wait, I never took a class!

Can I bother you for a pull request on this issue?

**Comment by rrthomas** [comment]
Sure, coming up.
