### ISSUE TITLE
"spent whenever" → "spent at any time"

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#455]
This occurs twice, in chapters 10 and 12. This change is needed, because "whenever" expects a condition (e.g. "whenever it rains"). (The usage is fine colloquially, but not great in the more formal context of this sort of book.)

**Comment by aantonop** [comment]
Fixed in bitcoinbook@74225613047570ffc7208ad66d4d63170ce1b8b1
