### ISSUE TITLE
Ch. 12: double-spending in payment channels

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#457]
The text says: "The two parties can then create commitment transactions that double-spend (No Double-Spend) the settlement on a shorter timelock (Timelock)."

Does it really mean to say "transactions that double-spend"? Surely double-spending is not possible? Should it just say "spend"? If not, some explanation is warranted! Or perhaps it should just say "cannot" rather than "can"?

**Comment by 30mb1** [comment]
@rrthomas More detailed explanations are presented later in the relevant chapter. The phrase is actually correct, because all commitment txns spend the same output (from settlement txn), but only one of them will bu pushed to blockchain in the end.

**Comment by rrthomas** [comment]
Thanks for the explanation.
