### ISSUE TITLE
Should digital signatures be explained in their own section in ch 4?

### ISSUE THREAD

**Issue by bg002h** [bitcoinbook/bitcoinbook#46]
Might make a nice section to add before discussing transactions.

Here are some graphics I've made a while ago to explain this concept.  Feel free to use them:

https://www.dropbox.com/s/33l2botzmtce5k4/EncryptLoop.svg
https://www.dropbox.com/s/4ew1dbsh1qb2ifg/SignLoop.svg

**Comment by enderminh** [comment]
I'll defer to Andreas, since this would be new text for him to write if he chooses to.

**Comment by aantonop** [comment]
Signatures may be covered in chapter 5 as part of transactions, not in
chapter 4.

On Wed, Jun 18, 2014 at 10:21 AM, Minh T. Nguyen notifications@github.com
wrote:

> I'll defer to Andreas, since this would be new text for him to write if he
> chooses to.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aantonop/bitcoinbook/issues/46#issuecomment-46441622.

## 

Andreas M. Antonopoulos
andreas@antonopoulos.com
Tel: +1 347 744 9404

**Comment by bg002h** [comment]
ACK.
