### ISSUE TITLE
Ch. 12: Payee vs Payer in HTLC

### ISSUE THREAD

**Issue by rrthomas** [bitcoinbook/bitcoinbook#460]
In the script to implement an HTLC, "Payee Pubic Key" should be "Payer Public Key" (two errors!). The refund should go to the payer, not the payee.

Similarly, later where it says "the payee can claim a refund", that should be "payer".

**Comment by aantonop** [comment]
Perhaps I can replace with names, to help disambiguate.

**Comment by aantonop** [comment]
Fixed in bitcoinbook@f66e7c5f0e01a7ac2ea24a49176b8ca14829a1e3
