### ISSUE TITLE
Ch. 02 Bob's tx id to Gopesh can't be found - imaginary - lie?

### ISSUE THREAD

**Issue by montvid** [bitcoinbook/bitcoinbook#468]
I can't seem to find the tx in 2bbac8bb3a57a2363407ac8c16a67015ed2e88a4388af58cf90299e0744d3de4 in Block Explorer for the tx of 0.01 to Gopesh - can you? Why mix real and imaginary tx? Bob DID NOT PAY Gopesh - it is a lie! Bob did not pay to ANYONE! See:
https://blockchain.info/address/1GdK9UzpHBzqzX2A9JFP3Di4weBwqgmoQA
Or here - no inputs to Gopesh or anyone:
https://blockchair.com/bitcoin/outputs?q=recipient(1GdK9UzpHBzqzX2A9JFP3Di4weBwqgmoQA)

Could someone add links instead of pictures of tx id's as I had to type the tx id myself to check...

**Comment by montvid** [comment]
Maybe let us add in the book a real tx id as there are a few in Bob's and change the story so it would not be that Bob scammed Gopesh?

**Comment by montvid** [comment]
A wonderful story how "Replace by Fee" was created! Bob tried to send btc to Gopesh but the btc bounced back because Bob did not use replace by fee to bump the miner fee as the initial fee was too small to be included in the block.

**Comment by montvid** [comment]
Okay, sorry, maybe I was trolling about the story but there is a fact that there is NO transaction from Bob to Gopesh on the blockchain - how do you explain that? There is Joe - Alice - Bob and that is all.

**Comment by aantonop** [comment]
I didn't fully develop the example, because I unfortunately lost Bob's private key. It was the early days of the book and I was sloppy with note-taking and key management on the examples. When I went back and added the Gopesh example, I no longer had Bob's key. Worse, people have been sending money to Bob's address, which is now burnt forever. 

Perhaps one day I will re-do all the stories for the third edition, once I can rewrite them to include Lightning.

**Comment by montvid** [comment]
@aantonop Thanks for the reply. I would suggest redoing/updating the examples with small amount of btc as now no one would pay such small prices for btc. The examples in the book don't reflect what is today.

A benefit would be that you would have the private key and could donate the btc people send in error to charity. Now it is gone forever useless. That could have been fixed in the Second Edition as you can't stop people doing this error and they are going to do this error in the future as a fact see a person in 20170831:
https://blockchain.info/tx/e6680df8309ee3d74f07d7a347d5aaa53ef3525221977a6a561012cf64b9d273
Please fix this for the sake of bitcoin. There is no use in getting btc stuck in unusable addresses.

**Comment by montvid** [comment]
@aantonop Another argument. Okay, you lost your private key. Generating a new key and redoing the SAME 3 transactions in the book would cost you 3x0.0005 BTC miner fee - less than 15$ as you are not actually paying anyone. Comparing 9+31 mistake transactions from other people who lost 0,01870887+0,25089525 BTC = 2100$ not calculating the miner fees they paid. Even if 1 person makes a mistake it costs him more than 15$ than for you to fix your mistake. This 2100$ could have gone to charity. Other mistaken tx can still go to charity if you fix this now.

Oh and when researching I found another mistake in the book. The tx values form Joe to Alice are incorrect - Joe sent 0.1 btc paying 0 fees NOT 0.1005 with a fee of 0.0005. So now we have two transaction mistakes in the book that cost less than 15$ to fix. See the tx in explorer:
https://blockchain.info/tx/7957a35fe64f80d234d76d83a2a8f1a0d8149a41d81de548f0a65a8a999f6f18
