### ISSUE TITLE
Ch. 02 block #277316, contains 419 transactions not 420

### ISSUE THREAD

**Issue by montvid** [bitcoinbook/bitcoinbook#469]
"Jing’s winning block became part of the blockchain as block #277316, containing 420 transactions, including Alice’s transaction." It is 419 - including the miner tx see:
https://blockchain.info/block-height/277316
https://blockexplorer.com/block/0000000000000001b6b9a13b095e96db41c4a928b97ef2d944a9b31b2cc7bdc4
https://blockchair.com/bitcoin/block/277316

**Comment by montvid** [comment]
I see that the first edition of Mastering Bitcoin has the 419 tx value but the second edition has the 420 - why? In Ch. 03 of the 2nd ed it is written that the block has 419 tx

**Comment by aantonop** [comment]
Fixed in bitcoinbook@1ac8b375e6fc3de1c5d8d8be7ff7fbc3e4fadb40
Apparently, we need regression testing as we introduced an error at some point.
