### ISSUE TITLE
Double-spending problem

### ISSUE THREAD

**Issue by vbuterin** [bitcoinbook/bitcoinbook#47]
The way I have started to talk about the double-spending problem (which I've also renamed "transaction reversal attacks") is:

Suppose that I have 100 BTC, and I sign a transaction sending the 100 BTC to you. Then, the next day, I also sign a transaction sending the same 100 BTC to my friend George. Both of those transactions cannot happen at the same time, so which one succeeds? The answer is, the one that came first. However, there is no way to cryptographically look at a piece of data and see when it was produced. Thus, there needs to be some kind of external mechanism that exists in order to keep time.

Feel free to use something like this.

**Comment by bg002h** [comment]
I use a clock analogy too. Bitcoin is, fundamentally, a clock. Each block is a tick. While transactions happen between parties in "between" ticks, transactions aren't added to the consensus ledger until the next tick. Thus, you have to wait for the clock to tick until you are sure that funds weren't spent twice.

**Comment by enderminh** [comment]
Thanks for sharing your ideas. However, I am going to close this issue, since it's not really a specific suggestion or change to the existing text.

If you have small, specific changes, feel free to raise them. Thanks though.
