### ISSUE TITLE
Ch. 02 Difficulty picture mbc2_0209 incorrect 

### ISSUE THREAD

**Issue by montvid** [bitcoinbook/bitcoinbook#471]
As the name "Figure 9. Alice’s transaction included in block #277316" suggests that it is about Alice tx so the Difficulty arrow should start from block 277316 as the difficulty to reverse Alice tx starts from that block, see here https://en.bitcoin.it/wiki/Confirmation

**Comment by wbnns** [comment]
@montvid 

Thank you. Closing this since it is a duplicate of #470.

**Comment by montvid** [comment]
#470 and #471 are two errors in the same picture. You have to fix both in the picture it is not a duplicate if you look at the picture yourself https://howieliux.github.io/assets/others/Mastering_bitcoin/images/mbc2_0209.png

**Comment by wbnns** [comment]
@montvid Apologies for missing this. Reopening; thanks for letting me know.

**Comment by montvid** [comment]
Thanks for fixing the book. Yeah, the picture is an epic fail. 🤣
