### ISSUE TITLE
chapter 7: five off-by-one errors for nSequence

### ISSUE THREAD

**Issue by bisqfan** [bitcoinbook/bitcoinbook#477]
I observed five off-by-one errors in the section "Original meaning of nSequence":

First sentence: the correct value is 2^32-1 (0xFFFFFFFF).
Last sentence of first paragraph: the correct value is 2^32-1
First sentence of second paragraph: the correct value is 2^32-1.
Last sentence of second paragraph: the correct values are 2^32-1 and 2^32-2 (0xFFFFFFFE)

**Comment by aantonop** [comment]
Yikes

**Comment by aantonop** [comment]
Fixed in bitcoinbook/bitcoinbook@ebbdbcf68382fb810bb3d025987c15680bc36f99
