### ISSUE TITLE
Chapter 8: "methodology"

### ISSUE THREAD

**Issue by bisqfan** [bitcoinbook/bitcoinbook#479]
In the section "Simplified Payment Verification (SPV) Nodes", the last sentence of the second paragraph uses the word methodology wrongly. Correct is: method.

The following paragraph represents a methodology (analysis of the methods), but SPV simply uses a method.

If you think that filing this issue is pedantic, you are certainly right and may ignore it.

**Comment by aantonop** [comment]
Fixed 81f6c7e
