### ISSUE TITLE
A few useful pictures that I made

### ISSUE THREAD

**Issue by vbuterin** [bitcoinbook/bitcoinbook#48]
http://vitalik.ca/files/address.png
http://vitalik.ca/files/fraud.png
http://vitalik.ca/files/nuhuh.png
http://vitalik.ca/files/sybil.png
http://vitalik.ca/files/spv.png

Fee free to modify or use at will.

**Comment by enderminh** [comment]
Thanks for sharing your ideas. However, I am going to close this issue, since it's not really a specific suggestion or change to the existing text/image.

Plus, I suspect that the folks over at O'Reilly are going to have to redo all of Andreas' images from scratch professionally anyways.
