### ISSUE TITLE
Chapter 3. source code compiling does not work at all...

### ISSUE THREAD

**Issue by leegod** [bitcoinbook/bitcoinbook#480]
I am very frustrating. for a whole day, can't progress any more. 
This book's chapter 3 description is too short and have a lot of missing parts of whole procedure of compiling and launch bitcoin system on my Window 10 computer. 

Exactly how to do it? Why error occur? How to step by step from nothing? I want youtube video please...

Specifically, page 33, github 'shell' does not described, so I googled and installed mingw64. Ok this is fine. But at page 35,  after type, $ ./autogen.sh, error says finally "please install autoconf first", but how?

and page 34, [Configuring the Bitcoin Core build], too short and does not describe at all, it just says see the doc/build-unix.md?  Then what about the case of window10? So I saw Window build doc. file, but at there too incomplete description. Totally messed.

Please help.

**Comment by aantonop** [comment]
The build instructions are for a Linux system. It is out of scope of this book to offer detailed build instructions for multiple operating systems. I might add that Windows is not the easiest system to configure as an open source development environment. Sorry!
