### ISSUE TITLE
Issues about numerical formula

### ISSUE THREAD

**Issue by jirlock** [bitcoinbook/bitcoinbook#487]
In the book(asciidoc), formulas look like below (at least on my browser(chrome)) and I think there is something wrong.

From ch04.asciidoc
\[\begin{equation} {y^2 = (x^3 + 7)}~\text{over}~(\mathbb{F}_p) \end{equation}\]

I think these appearances are not intended, so should be fixed.
Thank you for a great book !

**Comment by aantonop** [comment]
These are rendered correctly by the OReilly typesetting software that
includes latexmath extensions. Githubs asciidoc rendering doesn't do
latexmath, so we it doesn't show correctly. I'd rather not replace with
images. Let's leave it like this, for now

**Comment by jirlock** [comment]
I see. Thank you for the information!

**Comment by aantonop** [comment]
Thanks @jirlock !
