### ISSUE TITLE
minor mistakes in glossary?

### ISSUE THREAD

**Issue by rromanenko** [bitcoinbook/bitcoinbook#494]
SPV is mentioned twice, as an abbreviation and with full wording. If that's done on purpose, maybe it's better to just put a reference, not duplicate the explanation?

Also 

> Stale
> Block
> Block which were successfully mined but which isn’t included on the current best block chain

Shouldn't it be block which **was**?

**Comment by aantonop** [comment]
Thanks fixed 751fc89
