### ISSUE TITLE
Chapter 3 Examples 4-6 links are shown instead of the code 

### ISSUE THREAD

**Issue by nakao92** [bitcoinbook/bitcoinbook#498]
In Chapter 3 for examples 4-6, in the sample code I'm just seeing "link:code/rpc_transaction.py[]" or similar instead of the code that is stored in those folders.

PS Appreciate having this online, waiting on the paperback in the mail :)

**Comment by aantonop** [comment]
This renders correctly in the paper and ebook. Github's rendering engine doesn't do link preprocessor macros.
