### ISSUE TITLE
Clarify meaning of "orphan" block when a fork happens

### ISSUE THREAD

**Issue by philippgille** [bitcoinbook/bitcoinbook#500]
In chapter 10 the meaning of "orphan" is defined as follows:

> If a valid block is received and no parent is found in the existing chains, that block is considered an "orphan." Orphan blocks are saved in the orphan block pool where they will stay until their parent is received. Once the parent is received and linked into the existing chains, the orphan can be pulled out of the orphan pool and linked to the parent, making it part of a chain. Orphan blocks usually occur when two blocks that were mined within a short time of each other are received in reverse order (child before parent).

But later, when describing what happens when a fork occurs but the network reconverges, there's the following sentence:

> Any miners working on extending the chain star-upside-down-triangle will now stop that work because their candidate block is an "orphan," as its parent "upside-down-triangle" is no longer on the longest chain.

This is confusing, because the candidate block for the "star-upside-down-triangle" chain *has* a parent, which is "upside-down-triangle". So if the block has a parent, should it still be called "orphan" block?

**Comment by wbnns** [comment]
@philippgille 

Thanks for letting us know this was confusing to you. Here's more context, in case helpful:
https://en.bitcoin.it/wiki/Orphan_Block

Please feel free to open a pull request with any new wording you feel might have made this more clear when you read it, the first time around.

**Comment by philippgille** [comment]
@wbnns : Why did you immediately close this issue instead of entering a discussion or asking me for a proposal?

I didn't open this issue because I was confused by the wording. The two text sections clearly describe orphans _completely different_.

- The first section I quoted says: An orphan block is a (received) block where the node doesn't find a parent block in its chain
- The second section I quoted says: A block whose parent block is not on the longest chain (anymore)

So I opened this issue to raise awareness about this difference and potentially help fix this in an upcoming edition.

The page you linked to (bitcoin.it wiki) actually describes exactly the issue here, that people _erroneously_ call *stale* blocks *orphan* blocks.

So to get to a proposal: In the book's case, the first section I quoted correctly describe orphan blocks. But the other section should say *stale* blocks (as per the wiki you linked to).

WDYT? (I'd like to discuss this here before creating a PR)

**Comment by wbnns** [comment]
@philippgille 

Hello, apologies for misunderstanding you - thanks for clarifying.

>So to get to a proposal: In the book's case, the first section I quoted correctly describe orphan >blocks. But the other section should say stale blocks (as per the wiki you linked to).
>
>WDYT? (I'd like to discuss this here before creating a PR)

Ok, sure.
