### ISSUE TITLE
missing link for alt_libraries 

### ISSUE THREAD

**Issue by karthik-ir** [bitcoinbook/bitcoinbook#502]
Ch01. above **Quick Start** ,  link for alt_libraries takes nowhere

**Comment by wbnns** [comment]
Tested the 2nd edition and was able to successfully utilize the link. Suspecting that this may be related to an unofficial port of the book to digital format.

@karthik-ir Please let us know if this assertion is incorrect and we can take a closer look.

**Comment by peguerosdc** [comment]
Hi! I am facing the same issue with version `3e39371a1f5be9541018a819e82ff5d2cf89cc5f` (most recent as of today). Not sure if relevant, but tried with Firefox and Chrome.

EDIT: the [mining] link (Ch01, at the end of the penultimate parapraph) is not working either
