### ISSUE TITLE
Ch 02 Tx values form Joe to Alice are incorrect

### ISSUE THREAD

**Issue by montvid** [bitcoinbook/bitcoinbook#508]
The tx values form Joe to Alice are incorrect - Joe sent 0.1 btc paying 0 fees NOT 0.1005 with a fee of 0.0005. See also #468. See the tx in explorer:
https://blockchain.info/tx/7957a35fe64f80d234d76d83a2a8f1a0d8149a41d81de548f0a65a8a999f6f18

**Comment by aantonop** [comment]
Thanks fixed 5a64136
