### ISSUE TITLE
(Chapter 2) Block Explorer URL 

### ISSUE THREAD

**Issue by ryandasilva** [bitcoinbook/bitcoinbook#511]
Hello. Loving the book so far and all that Andreas does for Bitcoin. One thing that stood out to me right away was that in Example 1 of Chapter 2, it provides a link to "Alice's" bitcoin transaction. The link provided uses blockexplorer.com . Out of curiosity I tried to view the link and it pops up with an anti BTC message calling Blockstream's implementation of Bitcoin a defunct and legacy implementation that they are no longer supporting and they will be supporting Bitcoin Cash as the real bitcoin and will be only providing "legacy" support. I think this is a bad representation of bitcoin and that perhaps a more pro bitcoin block explorer like blockchain.info should be used . I haven't made it past chapter 2 yet but this would also apply to any URLs in other chapters that use blockexplorer.com .

**Comment by matkirch** [comment]
I agree -- all instances of Blockexplorer.com need to be replaced with another block explorer site...

**Comment by aantonop** [comment]
Yes, I agree. Time to change it for the next print

**Comment by aantonop** [comment]
Thank you, fixed 8ae3c05
