### ISSUE TITLE
Second edition on amazon.de

### ISSUE THREAD

**Issue by trulex** [bitcoinbook/bitcoinbook#519]
I want to support the author by purchasing the book, but it seems to me that amazon.de doesn't offer 2nd edition print 2, only print 1. Can someone verify or deny this? Thanks

**Comment by aantonop** [comment]
The differences between print 1 and print 2 are a couple of typos and a dedication page I added to commemorate my mother, who passed away the week print 1 came out. It is not material difference. 

https://www.amazon.de/Mastering-Bitcoin-Unlocking-Digital-Cryptocurrencies/dp/1491954388
