### ISSUE TITLE
Chapter 5: single leaked child private key, together with a parent chain code, reveals all the private keys of all the children

### ISSUE THREAD

**Issue by QingShiLuoGu** [bitcoinbook/bitcoinbook#520]
* single leaked child private key, together with a parent chain code, reveals all the private keys of all the children. Worse, the child private key together with a parent chain code can be used to deduce the parent private key.*

any explanation？

**Comment by jonathancross** [comment]
This is why hardened keys are used.

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#implications

> One weakness that may not be immediately obvious, is that knowledge of a parent extended public key plus any non-hardened private key descending from it is equivalent to knowing the parent extended private key (and thus every private and public key descending from it). This means that extended public keys must be treated more carefully than regular public keys. It is also the reason for the existence of hardened keys, and why they are used for the account level in the tree. This way, a leak of account-specific (or below) private key never risks compromising the master or other accounts.

**Comment by wll2007** [comment]
@jonathancross How deduce the parent private key to use the child private key together with a parent chain code?
