### ISSUE TITLE
Chapter 4: Link to pybitcointools is not relevent anymore

### ISSUE THREAD

**Issue by sindhoor7** [bitcoinbook/bitcoinbook#523]
Looks like Vitalik said bye bye to the code he wrote for bitcoin last year on Dec 15th. The referance of pybitcointools is no more valid.

https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch04.asciidoc#implementing-keys-and-addresses-in-python

**Comment by olivermaerz** [comment]
+1 

Just got the book and am disappointed that there is no update on how to generate addresses in Python without the no longer available pybitcointools (pybitcointools github repository is empty).

**Comment by wbnns** [comment]
@sindhoor7 Thanks for reporting the issue.

@OliverMaerz Here's a [link to the code](https://github.com/wbnns/pybitcointools) that you can use, so you can still follow along. Alternatively, you can also clone Vitalik's repo directly, and then roll back two commits to achieve the same effect.

Hope that helps.

**Comment by aantonop** [comment]
Petter Todd's python-bitcointools library is probably the closest
replacement

**Comment by aantonop** [comment]
Maybe we can use this issue to plan a replacement of the library reference
to a more suitable python library for the upcoming third edition release

**Comment by wbnns** [comment]
@aantonop Ok.

**Comment by wbnns** [comment]
I think we can just go with the fork that Vitalik mentions in his repo for now:
https://github.com/primal100/pybitcointools

We use this library for some code samples to help bridge a few fundamental concepts. I'm not sure if removing it does anything other than forcing a refactor to recreate the same points.

Closing for now, but will reopen if others disagree.
