### ISSUE TITLE
ch-04 why use "Most" not "all"

### ISSUE THREAD

**Issue by hellllll0world** [bitcoinbook/bitcoinbook#528]
I notice a sentence: "Most bitcoin transactions require a valid digital signature to be included in the blockchain". Why use the word "most" not "all" here? Is some transactions there without a valid digital signature in the blockchain? Can anyone explain it to me?

**Comment by mcdallas** [comment]
Bitcoin uses a scripting language that is used to specify the conditions under which someone can redeem the coins you are sending. 

Addresses that start with 1 are called pay-to-public-key-hash addresses and attach a specific script that requires a valid digital signature. 

You can use a Pay-to-script-hash address (the ones that start with a 3) and write your own verification script which can be anything you like (within the abilities of the scripting language). Your script does not have to verify a signature. You can even use an anyone-can-spend or none-can-spend script (also known as proof of burn).

**Comment by jonathancross** [comment]
The coinbase transaction also doesn't require a signature (because these coins are minted from nothing).

PS: This is not really a Q&A forum, questions like this should probably be asked on bitcoin.stackexchange.com

**Comment by hellllll0world** [comment]
Thanks.

**Comment by jonathancross** [comment]
@onceyoung Please close this issue.
