### ISSUE TITLE
Index link not working

### ISSUE THREAD

**Issue by lightningnetworkstores** [bitcoinbook/bitcoinbook#532]
Link to the index (https://github.com/bitcoinbook/bitcoinbook/blob/develop/index.asciidoc) is not working as mentioned here (https://github.com/bitcoinbook/bitcoinbook/blob/develop/book.asciidoc).

**Comment by wbnns** [comment]
@lightningnetworkstores 

Thanks for reporting. Taking a closer look, it appears the book would need to be compiled/printed, in order for the index to become populated, in order to pick up all of the references. We could link to `ix.html`, but that would be an empty file.

```
<section data-type="index"/>
```
Hope that helps clarify.
