### ISSUE TITLE
Chapter 12: confusing section "Applications from Building Blocks"

### ISSUE THREAD

**Issue by Quuxplusone** [bitcoinbook/bitcoinbook#538]
> Payment Channels.
> Quorum of Control + Timelock + No Double Spend + Nonexpiration + Censorship Resistance + Authorization. A multisig 2-of-2 (Quorum) with a timelock (Timelock) used as the “settlement” transaction of a payment channel can be held (Nonexpiration) and spent whenever (Censorship Resistance) by either party (Authorization). The two parties can then create commitment transactions that double-spend (No Double-Spend) the settlement on a shorter timelock (Time‐lock).

The property "Censorship Resistance" was not previously defined. (The word "censorship" appears only twice in the book, according to Ctrl+F!)

Furthermore, this entire paragraph is Greek to me. I do understand the concepts of "Digital Notary" and "Kickstarter" (although I don't understand what the word "Lighthouse" has to do with Kickstarter). But I don't understand what a "Payment Channel" is, and I don't understand the sentence

> A multisig 2-of-2 with a timelock used as the “settlement” transaction of a payment channel can be held and spent whenever by either party. The two parties can then create commitment transactions that double-spend the settlement on a shorter timelock.

Sounds kind of like "escrow," almost? Surely the phrase "double-spend" there is a mistake, and it maybe means more like "...that _instead_ spend the output by mutual consent before the timelock has expired"?

UPDATE: Ah, I see that the bulk of Chapter 12 is devoted to explaining "payment channels" in more detail. It remained Greek until the first sentence of the section titled "Simple Payment Channel Example." I wish the "Simple Payment Channel Example" had come first, and then all the stuff about "funding transaction" and "channel closure" and "timelock" and "double-spending" had come *afterward*... or something like that.

**Comment by Quuxplusone** [comment]
Page 289 in the PDF:

> The channel we just described works, but only if both parties cooperate, without any failures or attempts to cheat. Let’s look at some of the scenarios that break this channel and see what is needed to fix those:
> • Once the funding transaction happens, Emma needs Fabian’s signature to get any money back. If Fabian disappears, Emma’s funds are locked in a 2-of-2 and effectively lost. This channel, as constructed, leads to a loss of funds if one of the parties disconnects before there is at least one commitment transaction signed by both parties.
> • While the channel is running, Emma can take any of the commitment transactions Fabian has countersigned and transmit one to the blockchain. Why pay for 600 seconds of video, if she can transmit commitment transaction # 1 and only pay for 1 second of video? The channel fails because Emma can cheat by broadcasting a prior commitment that is in her favor.
> Both of these problems can be solved with timelocks [...]

The section goes on to describe a solution that *seems* overcomplicated. I'm sure I'm missing something here. *My* timelock-based solution would look like this:

- Emma publishes this funding transaction: "Emma commits 0.03600 BTC, redeemable by 2-of-2 (Emma and Fabian) — and/or, after 24 hours, redeemable by Emma acting alone."
- Emma transmits to Fabian this commitment transaction: "Redeem the funding transaction, sending 0.00001 BTC to Fabian and 0.03599 BTC back to Emma — signed, Emma." Fabian countersigns the transaction, but does not submit it to the network *and* does not transmit it back to Emma (because if he did that, Emma would be able to submit it to the network, and that would be bad). Fabian transmits 1 second of video to Emma.
- Emma transmits to Fabian another commitment transaction: "Redeem the funding transaction, sending 0.00002 BTC to Fabian and 0.03598 BTC back to Emma — signed, Emma." Fabian countersigns the transaction, but does not submit it to the network *and* does not transmit it back to Emma. Fabian transmits the next second of video to Emma.
- Worst case if Emma reneges and drops the connection: Fabian must remember to submit the final commitment transaction to the network within 24 hours, or else Emma will be able to steal all 0.03600 of her bitcoins back from the funding transaction.
- Worst case if Fabian reneges: Emma has sent Fabian a commitment transaction worth 0.00042 BTC, but has received only 41 seconds of video. Fabian countersigns and submits that transaction to the network. Emma is cheated out of 1 second's worth of video.

This doesn't seem any worse than the two complicated schemes described in the book. It seems on par with the Lightning Network example (page 298 in the PDF) in terms of simplicity. But maybe I'm missing something that would explain why all the complexity was necessary?

**Comment by Quuxplusone** [comment]
Now that I've finished Chapter 12, just one more point of confusion:

> Alice’s node then constructs an HTLC [...] with a 10-block refund timeout, for an amount of 1.003 bitcoin. [...] Alice offers this HTLC to Bob, deducting 1.003 bitcoin from her channel balance with Bob and committing it to the HTLC. The HTLC has the following meaning: “Alice is committing 1.003 of her channel balance to be paid to Bob if Bob knows the secret, or refunded back to Alice’s balance if 10 blocks elapse.”

Later:

> Now, Diana has secret `R`. Therefore, she can now claim the HTLC from Carol. Diana transmits `R` to Carol and adds the 1.001 bitcoin to her channel balance [...]

The apparent problem with the protocol described in the book is that after Diana uses `R` to claim her 1.001 BTC, she has no incentive to send `R` on to Carol. The apparent solution is that the HTLCs involved must not be of the form "... if Bob [_knows_](https://en.wikipedia.org/wiki/Zero-knowledge_proof) the secret `R`"; they must actually be of the form "... if the unlocking script _contains a plaintext copy_ of `R` digitally signed by Bob."

This solution ensures that Eric cannot claim his 1 BTC without publicizing the value of `R` into the blockchain. As soon as Eric publicizes `R`, Diana and Carol and Bob will race to claim their own HTLCs using that `R` (digitally signed by themselves, so that nobody else in the world can use the now-public `R` to claim the HTLCs associated with Diana or Carol or Bob).

This solution works in my head, but it is not clear from the book whether this is _actually_ how Lightning Network works in practice, or if they have another approach. (They might not want to use the solution described here if it would be plausible to somehow [deny](https://en.wikipedia.org/wiki/Denial-of-service_attack) the mining of Eric's transaction(s) which publicly reveal `R`; this would mean that Diana and Carol and Bob collect their HTLCs based on the _transmission_ of Eric's transaction(s) but Eric's transaction(s) are never _mined_; essentially Diana steals the money that Alice meant to send to Eric. I think such an attack is implausible but I don't know.)

**Comment by wbnns** [comment]
@Quuxplusone 

Thank you for spending the time to share these ideas. We'll keep this on-hand as we look to make further improvements to these sections. For specific questions, you may want to check out [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/).

Also, if you'd like to learn more specifically about the Lightning Network, please check out [Mastering the Lightning Network](https://github.com/lnbook/lnbook). It's also here on GitHub, and is currently being worked on. It's due to be published later this year.

Hope that helps.
