### ISSUE TITLE
Ch 5 – Transaction LifeCycle

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#54]
”Once recorded on the blockchain and confirmed by sufficient subsequent blocks (confirmations), the transaction is a permanent part of the bitcoin ledger and is accepted as valid by all participants. ”

The same problem here as discussed in issue #18.  The text gives the impression that subsequent blocks are needed before a transaction is confirmed.

**Comment by enderminh** [comment]
I changed it to

"Once confirmed on the blockchain in the first block and supported by sufficient subsequent blocks (additional confirmations), the transaction becomes a permanent part of the bitcoin ledger..."

Hope this is better.
