### ISSUE TITLE
Bloom filter confusion

### ISSUE THREAD

**Issue by morfies** [bitcoinbook/bitcoinbook#541]
> The accuracy depends on the number of patterns added versus the size of the bit array (N) and number of hash functions (M). A larger bit array and more hash functions can record more patterns with higher accuracy. A smaller bit array or fewer hash functions will record fewer patterns and produce less accuracy.

According to context before. I think more hash functions(larger M) will lead to more bits to be set, then less accuracy instead, as every hash function needs to be run in turn.

**Comment by wbnns** [comment]
@morfies Thanks.
