### ISSUE TITLE
CH07-why Alice can no longer spend the money because it’s locked with Bob’s key?

### ISSUE THREAD

**Issue by zhouguoguo** [bitcoinbook/bitcoinbook#542]
In Ch07 timelock introduction, if Alice spend a UTXO with CLTV setting 3 months later, she must set the transaction nLockTime larger than CLTV time, we say 3 month plus 2 days. In this case, after Alice pay Bob then Bob can spend the output after 3 months and 2 days.
Then during the time before Bob can spend the output, Alice can again send a transaction to Charlie comsuming the same output which CLTV. Then she can set the new transaction's nLocktime the day before Bob can spend the UTXO Alice send to him.
If my understanding is right, how can I understand "Alice can no longer spend the money (because it’s locked with Bob’s key) "?

**Comment by wbnns** [comment]
@zhouguoguo 

This would be a good example of something to bring up on [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) if you're still unclear.

Hope this helps!
