### ISSUE TITLE
Ch 05 - Script Construction (Lock + Unlock)

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#55]
In the third paragraph under Script Construction (Lock + Unlock):
“In this book we refer to it as an "unlocking script" to acknowledge the much broader range of locking script requirements, as not all unlocking scripts must contain signatures.”

Perhaps “locking script requirements” should be “unlocking script requirements" ?

**Comment by enderminh** [comment]
I changed it to

In this book we refer to it as an "unlocking script", again, to acknowledge the range of possibilities of the scripting technology, as not all unlocking scripts must contain signatures.

with commit 9cfb054fb13edce68b42020777c2b036447f8c49
