### ISSUE TITLE
Ch05, some confusion in section "Private child key derivation" for HD wallet

### ISSUE THREAD

**Issue by rszheng** [bitcoinbook/bitcoinbook#552]
In line 336, 

> The parent public key, chain code, and the index number are combined and hashed with the HMAC-SHA512 algorithm to produce a 512-bit hash. This 512-bit hash is split into two 256-bit halves. The right-half 256 bits of the hash output become the chain code for the child. The left-half 256 bits of the hash are added to the parent private key to produce the child private key. In Extending a parent private key to create a child private key, we see this illustrated with the index set to 0 to produce the "zero" (first by index) child of the parent.

it says that "The left-half 256 bits of the hash are added to the parent private key to produce the child private key", but this is not right for the children of index from 0 to 2^31-1. For those children, their private keys are derived WITHOUT using their parent's private key, but rather their parent's public key! This is very import, since otherwise one can never figure out how it is possible to use only extended public key to create child public keys, as mentioned in line 361: 

> Extended keys are stored and represented simply as the concatenation of the 256-bit key and 256-bit chain code into a 512-bit sequence. There are two types of extended keys. An extended private key is the combination of a private key and chain code and can be used to derive child private keys (and from them, child public keys). An extended public key is a public key and chain code, which can be used to create child public keys (public only), as described in [public_key_derivation].

Therefore, some correction should be done to clear the confusion.

**Comment by wbnns** [comment]
@rszheng Thank you, we'll fix this.
