### ISSUE TITLE
Chap 3 - Building Bitcoin Core Executables

### ISSUE THREAD

**Issue by probablyangg** [bitcoinbook/bitcoinbook#565]
./autogen.sh and ./configure.sh work fine, but make produces the following error: 

```
Makefile:838: recipe for target 'chainparams.o' failed
make[3]: *** [chainparams.o] Error 1
make[3]: Leaving directory '/home/angelag/bitcoin/src'
Makefile:860: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/angelag/bitcoin/src'
Makefile:652: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/angelag/bitcoin/src'
Makefile:509: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
`
here is the entire output for the make command : https://pastebin.com/tfs7nb8b

**Comment by maflcko** [comment]
boost `list_of()` has been removed in the most recent release. So at least that should have been fixed.

**Comment by behradkhodayar** [comment]
Have you fixed it @angelagilhotra ? Does your machine meet dependencies ?!

**Comment by wbnns** [comment]
@nglglhtr 

Please let us know if you're still encountering an issue following the instructions, and we can reopen this to take a closer look.
