### ISSUE TITLE
Chapter5 - Public key used in child KDF is compressed, not uncompressed

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinbook/bitcoinbook#567]
Hello,

I think there is an error in chapter 5, [subsection Private child key derivation] (https://github.com/bitcoinbook/bitcoinbook/blob/second_edition_print3_rc2/ch05.asciidoc#private-child-key-derivation).

It says: 
> The child key derivation functions are based on a one-way hash function that combines:
> - A parent private or public key (ECDSA uncompressed key)
> - A seed called a chain code (256 bits)
> - An index number (32 bits)

But BIP32 child key derivation functions always take **compressed** ECDSA public key as argument.
From BIP32:
> serP(P): serializes the coordinate pair P = (x,y) as a byte sequence using SEC1's compressed form: (0x02 or 0x03) || ser256(x), where the header byte depends on the parity of the omitted y coordinate.

Note that all the diagrams in chapter 5 correctly show "Parent Public Key (264 bits)", the length of a compressed public key.

**Comment by sanjays95** [comment]
Yes. Even i think what you mentioned is right.

**Comment by wbnns** [comment]
@Janaka-Steph @sanjays95 Thank you both.

This has already been fixed on the `develop` branch.
