### ISSUE TITLE
Remove obsolete Coinprism from chapter 12 

### ISSUE THREAD

**Issue by oboukli** [bitcoinbook/bitcoinbook#575]
Coinprism shut down

**Comment by MartyIX** [comment]
Yes, please see: https://en.bitcoin.it/wiki/Coinprism#History

```
Coinprism shut down: March 31st, 2018[10]
```

**Comment by michaelbnewman** [comment]
As of February 2019, the entire section on colored coins is obsolete. Even the Colu colored coins have disappeared and reemerged as an ERC-20 CLN token. Their token apparently launched on Ethereum mainnet on February 11, 2018. See contract: https://etherscan.io/token/0x4162178b78d6985480a308b2190ee5517460406d
and contract creation event: https://etherscan.io/tx/0xc5e70ce0ff5065c4f1dd113eeb2d62223288543f55f94b96dda62c9a9f6efbb9
And on their website they are calling themselves a Dapp now: https://cln.network/

**Comment by wbnns** [comment]
@oboukli @MartyIX @michaelbnewman 

Thank you. Removed with #681.
