### ISSUE TITLE
Chapter 5 Missing information about account discovery and gap limit

### ISSUE THREAD

**Issue by Parz-val** [bitcoinbook/bitcoinbook#578]
Chapter 5 did not explain how wallet software figures out which addresses (from an extremely large pool) contain funds in deterministic wallets.  This is a very important part of the puzzle if one imports just the seed from an external source.  When a wallet or user does not respect this specification the account balance may be wrong.  The funds are not lost but would not show up in the wallet if the gap limit is not respected.

# Account discovery
When the master seed is imported from an external source the software should start to discover the accounts in the following manner:

derive the first account's node (index = 0)
derive the external chain node of this account
scan addresses of the external chain; respect the gap limit described below
if no transactions are found on the external chain, stop discovery
if there are some transactions, increase the account index and go to step 1
This algorithm is successful because software should disallow creation of new accounts if previous one has no transaction history, as described in chapter "Account" above.
Please note that the algorithm works with the transaction history, not account balances, so you can have an account with 0 total coins and the algorithm will still continue with discovery.

## Address gap limit
Address gap limit is currently set to 20. If the software hits 20 unused addresses in a row, it expects there are no used addresses beyond this point and stops searching the address chain. We scan just the external chains, because internal chains receive only coins that come from the associated external chains.

Wallet software should warn when the user is trying to exceed the gap limit on an external chain by generating a new address.

[source BIP44 account discovery](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account_discovery
)

**Comment by wbnns** [comment]
@Parz-val Thanks for suggesting how we can improve this section.

**Comment by krupawan5618** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/896
