### ISSUE TITLE
Suggestion to add Ruby code for Transactions processing

### ISSUE THREAD

**Issue by Sjors** [bitcoinbook/bitcoinbook#58]
About a year ago I gave a [presentation](http://www.slideshare.net/Provoost/bitcoin-transaction-in-ruby) about bitcoin transactions. It came with a Ruby [gist](https://gist.github.com/Sjors/5574485) that takes basic information from blockchain.info, constructs a transaction and prints out the hex for the user to copy paste and submit.

**Comment by aantonop** [comment]
This could be useful, but would need to be broken into 5-6 separate recipes that each is self-contained and demonstrates part of the solution. For example, one recipe to retrieve UTXO from blockchain. One recipe to sort UTXO to create the payment amount with the least amount of change and dust. One recipe to create the output scripts. One recipe to sign the inputs. One recipe to convert a private key to a public key. One recipe to create an address from a public key. 

If you would like to see some of your code included in the book, perhaps you could break it into code snippets that are self-contained and no more than half a page each, showing one concept only per snippet. 

Many thanks!

**Comment by Sjors** [comment]
That makes sense. But in that case you'll have to wait until I implemented transactions in Swift. That will be a lot more modular than my Ruby example and will have tests. It should also be more complete with respect to change. I'll know what dust is by then too :-)
