### ISSUE TITLE
chapter05: Risk of Extend Public Key not so understandable

### ISSUE THREAD

**Issue by scorpiozj** [bitcoinbook/bitcoinbook#581]
> However, because the xpub contains the chain code, if a child private key is known, or somehow leaked, it can be used with the chain code to derive **_all the other child private keys_**. A single leaked child private key, together with a parent chain code, reveals all the private keys of all the children. 

This is at the beginning of Hardened child key derivation. For "all the other child private keys", does it mean the sibling child private keys of the leaked child private key or child private keys of the leaked private key? I think it mean the latter, and it should be more specifically if it mean the latter.  
correct me if I'm wrong.

**Comment by wbnns** [comment]
@scorpiozj 

Hello, it refers to all child private keys associated with the parent. Hope that helps clarify.
