### ISSUE TITLE
chapter08: request the full block data 

### ISSUE THREAD

**Issue by didongke** [bitcoinbook/bitcoinbook#583]
The node missing these blocks will then retrieve them, by issuing a series of getdata messages requesting the full block data and identifying the requested blocks using the hashes from the inv message.

I think it should be : 

The node missing these blocks will then retrieve them, by identifying the requested blocks using the hashes from the inv message and issuing a series of getdata messages requesting the full block data.

**Comment by wbnns** [comment]
@didongke 

Thanks for the suggestion. The latter paragraph seems a bit more difficult to parse. Let's leave as-is for now, and if others disagree we can reconsider the change.
