### ISSUE TITLE
Chapter 10 Hashrate mistake

### ISSUE THREAD

**Issue by gmr81** [bitcoinbook/bitcoinbook#587]
Page 247. 
2010 initial Hashrate is 8MH/sec - final Hashrate is 116GH/sec (14500x growth)
2011 initial Hashrate is 16GH/sec - final hashrate is 9TH/sec (562x growth)

I think initial hashrate in 2011 shoud be 116GH as the final 2010 hashrate.
https://bitinfocharts.com/comparison/bitcoin-hashrate.html this confirm the data.

At this point the correct growth rate for year 2011 is 77.59x and not 562.

Am I missing something? I dont think so.
I would appreciate my name among the Authors of the book :-)
My name next to the Andreas' one ....I could die happily :-)

thanks in advance

P.S. I've just noticed that there are other mistakes:
2014:
From 10PH to 300PH is a 30x growth not 3000.
2015:
From 300PH to 800PH is a 2.66x growth not 266
2016:
From 800PH to 2.5EH OS a 3.12x growth not 312

**Comment by wbnns** [comment]
@gmr81 

Thank you for mentioning this.
