### ISSUE TITLE
Chapter 6: Pay-to-Public-Key-Hash (P2PKH) ---> Wrong validation script?

### ISSUE THREAD

**Issue by AnejaBK** [bitcoinbook/bitcoinbook#593]
In the book on page 136:

> For example, let’s look at Alice’s payment to Bob’s Cafe again. Alice made a payment of 0.015 bitcoin to the cafe’s bitcoin address. That transaction output would have a locking script of the form:
> 
> OP_DUP OP_HASH160 <Cafe Public Key Hash> OP_EQUALVERIFY OP_CHECKSIG
> The Cafe Public Key Hash is equivalent to the bitcoin address of the cafe, without the Base58Check encoding. Most applications would show the public key hash in hexadecimal encoding and not the familiar bitcoin address Base58Check format that begins with a "1."
> 
> The preceding locking script can be satisfied with an unlocking script of the form:
> 
> (Cafe Signature) (Cafe Public Key)

Shouldn't be:
(Alice’s Signature) (Alice’s Public Key)?

> The two scripts together would form the following combined validation script:
> 
> (Cafe Signature) (Cafe Public Key) OP_DUP OP_HASH160
> (Cafe Public Key Hash) OP_EQUALVERIFY OP_CHECKSIG

And here:
(Alice’s Signature) (Alice’s Public Key)  OP_DUP OP_HASH160
(Cafe Public Key Hash> OP_EQUALVERIFY OP_CHECKSIG

Each transaction has to have a proof for spending the input transaction as well as set the condition for spending it in the next transaction - or did I miss something? I am a beginner:)

**Comment by wbnns** [comment]
@AnejaBK 

The payment is going to the Cafe, not Alice (that is why the Cafe is being referenced).
