### ISSUE TITLE
Running ec-math.py results in lamba error

### ISSUE THREAD

**Issue by robermann** [bitcoinbook/bitcoinbook#596]
When running the Example 4-7 ([ec-math.py](https://github.com/bitcoinbook/bitcoinbook/commit/7ed95b283b707dac124c4fdc96d9f259e5297621)), I get the following error:

```
$ python ec-math.py
Traceback (most recent call last):
  File "ec-math.py", line 48, in <module>
    secret = random_secret()
  File "ec-math.py", line 29, in random_secret
    return convert_to_int(byte_array)
  File "ec-math.py", line 23, in <lambda>
    convert_to_int = lambda array: int("".join(array).encode("hex"), 16)
TypeError: sequence item 0: expected str instance, int found
```

**Comment by wbnns** [comment]
@robermann Apologies for the trouble. This should be fixed now, just make sure your local copy of the repository is updated and that you're using Python 3.
