### ISSUE TITLE
Coinprism example not working

### ISSUE THREAD

**Issue by robermann** [bitcoinbook/bitcoinbook#599]
Chapter 12: please note that links "https://www.coinprism.info/" and "https://www.coinprism.info/tx/10d7c4e022f35288779be6713471151ede967caaa39eecd35296aa36d9c109ec" are not working anymore. Actually coinprism has closed, see https://www.coindesk.com/blockchain-startup-coinprism-to-shut-down-in-2-days/amp/

Perhaps add some comment on the book, or remove the example from the next edition.

**Comment by wbnns** [comment]
@robermann 

Thank you, this has already been removed.
