### ISSUE TITLE
Chapter 4 asciidoc - #appdx_bx link broken

### ISSUE THREAD

**Issue by theagilecoder** [bitcoinbook/bitcoinbook#606]
The appendix page link is used at many places in the chapter 4 asciidoc but the link does not work. Probably the link is wrong.

**Comment by wbnns** [comment]
@theagilecoder 

This happens when the book is being read directly out of the GitHub repository, or if it isn't compiled correctly. When reading an official digital release of the book, there should be no issue utilizing the embedded links to navigate back and forth throughout the chapters.
