### ISSUE TITLE
Shouldn't bitcoinbook/ch07.asciidoc, Data Recording Output (RETURN) should say ...(OP_RETURN)

### ISSUE THREAD

**Issue by illBeRespawned** [bitcoinbook/bitcoinbook#607]
https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch07.asciidoc
states Data Recording Output (RETURN)
but I think it is talking about OP_RETURN as there is no "RETURN" Opcode in Bitcoin Script.
see:
https://en.bitcoin.it/wiki/Script

So it should say:
"Data Recording Output (OP_RETURN)"

If nobody objects I'd start a pull for that.

**Comment by wbnns** [comment]
@illBeRespawned Thank you for raising the issue, however, the convention used in the chapter was to not include the `OP_`. For example, in addition to `RETURN`, other operations also do not have the `OP_` included:

+ `CHECKSEQUENCEVERIFY`
+ `EQUAL`
+ `VERIFY`
+ `CHECKSIG` 

If `RETURN` were updated, the rest of the syntax should also be updated.
