### ISSUE TITLE
ch 3. hd_wallets link is broken

### ISSUE THREAD

**Issue by prosonf** [bitcoinbook/bitcoinbook#617]
- Page: [https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch03.asciidoc](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch03.asciidoc)
- Broken link [hd_wallets](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch03.asciidoc#hd_wallets)
- Contextual text: 

    > BIP-39 and BIP-32 (see [mnemonic_code_words] and [hd_wallets]).

**Comment by wbnns** [comment]
Hello, this happens when the book is being read directly out of the GitHub repository, or if it isn't compiled correctly. When reading the officially released digital copy of the book, there should be no issue utilizing the embedded links to navigate back and forth through the book.
