### ISSUE TITLE
Ch06: Contradictory description of the validity conditions of script execution

### ISSUE THREAD

**Issue by s-tikhomirov** [bitcoinbook/bitcoinbook#621]
The tip in the [A simple script](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc#a-simple-script) section says:

>Transactions are valid if the top result on the stack is TRUE (noted as &#x7b;0x01&#x7d;), any other nonzero value, or if the stack is empty after script execution.

Then, in the section [Separate execution of unlocking and locking scripts](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc#separate-execution-of-unlocking-and-locking-scripts):

> If the result of executing the locking script with the stack data copied from the unlocking script is "TRUE," the unlocking script has succeeded in resolving the conditions imposed by the locking script and, therefore, the input is a valid authorization to spend the UTXO. If any result other than "TRUE" remains after execution of the combined script, the input is invalid because it has failed to satisfy the spending conditions placed on the UTXO.

So what are the validity conditions? Does the empty stack and non-zero values are than FALSE indicate a valid execution?

**Comment by in3rsha** [comment]
A script is valid if there is only **one element** left on the stack and it is **not `OP_0`** (e.g. `OP_1` or a _data push_).
