### ISSUE TITLE
Ch06: Definition of dangling operator

### ISSUE THREAD

**Issue by s-tikhomirov** [bitcoinbook/bitcoinbook#622]
>If the unlocking script is executed without errors (e.g., it has no "dangling" operators left over)

What is a dangling operator?

(I assume these could be situations like ```2 OP_ADD``` -- an n-argument operation given less than n arguments -- but I'd like to see more clarity on this.)

**Comment by wbnns** [comment]
It seems the more conventional way of referring to this may have been as a `dangling pointer`:
https://en.wikipedia.org/wiki/Dangling_pointer
