### ISSUE TITLE
Ch07: "Complex script without P2SH" example without dummy value

### ISSUE THREAD

**Issue by s-tikhomirov** [bitcoinbook/bitcoinbook#624]
The [example](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch07.asciidoc#without_p2sh) provides a multisig unlocking script as ```Sig1 Sig2```. Should it be ```0 Sig1 Sig2``` due to a bug described [earlier](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch07.asciidoc#multisig_bug)?

**Comment by wbnns** [comment]
Nice catch, thanks for mentioning.
