### ISSUE TITLE
Ch10: Number of blocks in four years

### ISSUE THREAD

**Issue by michaelbnewman** [bitcoinbook/bitcoinbook#626]
In Chapter 10:

> …​where 21240 is the number of blocks in four years.

The correct number is 210240. Note, the P formula given above this text error has the correct 210240 number in it.

4 years * 365 days * 24 hours/day * 60 minutes/hour * 1 block/10 minutes
`>>> 4 * 365 * 24 * 60 * (1/10)`
`210240.0`

**Comment by wbnns** [comment]
@michaelbnewman 

Thank you. This has been resolved by #672.
