### ISSUE TITLE
Appendix D. SegWit

### ISSUE THREAD

**Issue by sammyne** [bitcoinbook/bitcoinbook#632]
# Question 

In the The **Why Segregated Witness?** section 
**Offline Signing Improvement** says **Segregated Witness signatures incorporate the value (amount) referenced by each input in the hash that is signed.** 

Could somebody explains what the **incorporation** means in more detail?

**Comment by matmaer** [comment]
Erm this is not a forum...  nor a chat room.

**Comment by wbnns** [comment]
@sammyne 

Hello, here's a link to the Bitcoin improvement proposal ([BIP-141](https://en.bitcoin.it/wiki/BIP_0141)) that introduced SegWit, which goes into more detail. Hope that helps.
