### ISSUE TITLE
Ch04: Remove section on BIP 38

### ISSUE THREAD

**Issue by mikong** [bitcoinbook/bitcoinbook#635]
Reference: https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki

The comments summary is "Unanimously Discourage for implementation". The comment from Greg Maxwell provides a good short explanation:

> This BIP has an unfortunate accidental history. Due to a process screw up it was never published for public review and has a number of shortcomings that would have been otherwise fixed. No strong replacement has been tendered because the general application of a single key paper wallet is strongly disfavored for security and usability reasons. I recommend against implementing this proposal. --Greg Maxwell, 2017-03-14

Here's a link to the full comments/discussion:

https://github.com/bitcoin/bips/wiki/Comments:BIP-0038

**Comment by wbnns** [comment]
@mikong 

Thank you.
