### ISSUE TITLE
Chapter 5: Non-existing Link?

### ISSUE THREAD

**Issue by EAWF** [bitcoinbook/bitcoinbook#640]
The master private key (m) then generates a corresponding master public key (M) using the normal elliptic curve multiplication process m * G that we saw in [pubkey].

When clicking on the pubkey link the page goes nowhere.

**Comment by wbnns** [comment]
@EAWF 

Hello, this happens when the book is being read directly out of the GitHub repository, or if it isn't compiled correctly. When reading the officially released digital copy of the book, there should be no issue utilizing the embedded links to navigate back and forth through the book.
