### ISSUE TITLE
Third print of second edition was already released

### ISSUE THREAD

**Issue by danra** [bitcoinbook/bitcoinbook#646]
The third print of the second edition seems to have already been released (at least, that's what what I'm reading says: "2018-03-23: Third Release").

1) This isn't mentioned in the releases, I guess the tag and release description should be updated?
2) `README.md` still incorrectly mentions the second print as the last one.
3) The link to Amazon says it links to the second print, I guess whoever orders the book will get the third print. I think it makes sense to just drop the "Second Print" in the preface to the Amazon link.

**Comment by wbnns** [comment]
@danra 

Hello. Could you please clarify where you got the version that was referencing `2018-03-23: Third Release`? On Amazon?

**Comment by danra** [comment]
Hi, no, bought in a book store

**Comment by aantonop** [comment]
You are correct, there was a third print. It moved the SegWit stuff into a
chapter, in the second print it was an appendix. It also fixed a few small
errors. That's all.

I didn't update the README. We should do that!

**Comment by wbnns** [comment]
Ah, ok! Updated with 8cbb757. 👍

@danra Thanks for mentioning!

**Comment by danra** [comment]
Cool, thank you Will!

**Comment by danra** [comment]
@wbnns Would be nice to also sort out the GitHub releases. Looks like the "second edition third print" release is marked as "pre-release" in the Releases page even though it's already out. Also, there's a second_edition_print3_rc2 tag with no release associated with it.

**Comment by wbnns** [comment]
@danra Thanks for mentioning. Opened #916. 👍
