### ISSUE TITLE
ch05.asciidoc Unreadable Chars?

### ISSUE THREAD

**Issue by EAWF** [bitcoinbook/bitcoinbook#654]
Regarding https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch05.asciidoc#navigating-the-hd-wallet-tree-structure, is it just me, or is the character encoding not set correctly. Seems to be this section of the chapter.

**Comment by aantonop** [comment]
It is set correctly for the rendering system used to produce the print and ebook versions, not for the Github rendering. We have to prioritize the formatting of the print and ebook over Github which is much more limited in its rendering abilities.

**Comment by EAWF** [comment]
OK, it was just that the rest of the characters above are set using the 
' character, so since the different characters were located at the 
bottom, I assumed( yeah, I know) that the lesser of the difference were 
not correct.

Thanks.
