### ISSUE TITLE
bitcore playground no longer available

### ISSUE THREAD

**Issue by morenoh149** [bitcoinbook/bitcoinbook#657]
https://github.com/bitcoinbook/bitcoinbook/blob/develop/appdx-bitcore.asciidoc

https://bitcore.io/playground 404s

**Comment by wbnns** [comment]
@morenoh149 

Thank you.

**Comment by morenoh149** [comment]
fwiw I think recommending https://github.com/bcoin-org/bcoin would save some headaches as it's still maintained
