### ISSUE TITLE
ch02: Note: fractional values

### ISSUE THREAD

**Issue by sunwukonga** [bitcoinbook/bitcoinbook#660]
> The bitcoin network can transact in fractional values, e.g., from millibitcoin (1/1000th of a bitcoin) down to 1/100,000,000th of a bitcoin, which is known as a satoshi. Throughout this book, we’ll use the term “bitcoin” to refer to any quantity of bitcoin currency, from the smallest unit (1 satoshi) to the total number (21,000,000) of all bitcoin that will ever be mined.

Technically, the bitcoin network transacts in satoshi. External tools translate the satoshi value into bitcoin. It's misleading to imply that the main unit is bitcoin.

**Comment by wbnns** [comment]
The most common vernacular reference would be bitcoin (yes, this may change over time).
