### ISSUE TITLE
Hardened child key derivation

### ISSUE THREAD

**Issue by Liangzx** [bitcoinbook/bitcoinbook#662]
"However, because the xpub contains the **chain code**, if a child private key is known, or
somehow leaked, it can be used with the chain code to derive all the other child pri‐
vate keys. A single leaked child private key, together with a parent chain code, reveals
all the private keys of all the children. Worse, the child private key together with a
parent chain code can be used to deduce the parent private key."

1. **chain code**  is parent's chain code?
2. if 1 true why it together with a  child private key can  reveals all the private keys of all the children?
![image](https://user-images.githubusercontent.com/13699123/67771337-128edd80-fa93-11e9-8cf2-33c442daaf17.png)

it means kowns 1 and 2 then all child privates keys konws?

**Comment by andronoob** [comment]
https://bitcoin.stackexchange.com/questions/56916/derivation-of-parent-private-key-from-non-hardened-child
