### ISSUE TITLE
Ch06 --Separate execution of unlocking and locking scripts

### ISSUE THREAD

**Issue by ariesunny** [bitcoinbook/bitcoinbook#665]
In Ch06:Separate execution of unlocking and locking scripts
> First, the unlocking script is executed, using the stack execution engine. If the unlocking script is executed without errors (e.g., it has no "dangling" operators left over), **the main stack is copied and the locking script is executed.** If the result of executing the locking script with the stack data copied from the unlocking script is "TRUE," the unlocking script has succeeded in resolving the conditions imposed by the locking script and, therefore, the input is a valid authorization to spend the UTXO. 

**1, What exactly the main stack here is? The result of the unlocking script or the raw data of the unlocking script.
2, It says the unlocking script is executed firstly, which is mismatch with the P2SH processing procedure in CH07.**
In CH07: Pay-to-Script-Hash (P2SH)
> 
![image](https://user-images.githubusercontent.com/30827440/68266199-57b1a180-0089-11ea-83fc-fb0653960007.png)

>The two scripts are combined in two stages. First, the redeem script is checked against the locking script to make sure the hash matches:
` <2 PK1 PK2 PK3 PK4 PK5 5 CHECKMULTISIG> HASH160 <redeem scriptHash> EQUAL`

>If the redeem script hash matches, the unlocking script is executed on its own, to unlock the redeem script:
`<Sig1> <Sig2> 2 PK1 PK2 PK3 PK4 PK5 5 CHECKMULTISIG`

**Why here it says the locking script ` <2 PK1 PK2 PK3 PK4 PK5 5 CHECKMULTISIG> HASH160 <redeem scriptHash> EQUAL` is process firstly?And does it miss a  DUP before the the locking script**

Thanks!!

**Comment by wbnns** [comment]
@ariesunny 

This would be a good example of something to bring up on [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) if you're still unclear.

Hope this helps.
