### ISSUE TITLE
Chapter 2: block-height URL broken

### ISSUE THREAD

**Issue by motorina0** [bitcoinbook/bitcoinbook#676]
**Section**:

You can see the block that includes https://blockchain.info/block-height/277316 [Alice's transaction].

**Steps**:
 - paste `https://blockchain.info/block-height/277316` in the browser URL bar

**Result**
 - a redirect to `https://www.blockchain.com/btc/block-height/277316` takes place (the `.com` domain)
  - `Unknown Error` - is displayed
  - HTTP status: `500 Internal Server Error`

**Comment by motorina0** [comment]
Similar scenario for: `https://blockchain.info/strange-transactions`
**Location**: https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc#bitcoin-addresses-balances-and-other-abstractions

**Comment by wbnns** [comment]
@motorina0

Thank you, this has already been fixed in Chapter 2, and we've pushed a16500e to resolve the issue with the strange transactions link; it seems that's no longer available on Blockchain.info.
