### ISSUE TITLE
Chapter 04: Missing subscript for P3

### ISSUE THREAD

**Issue by motorina0** [bitcoinbook/bitcoinbook#679]
**Location**:
https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch04.asciidoc#elliptic-curve-cryptography-explained

**Actual Text**
> the tangent line will be exactly vertical, in which case P3 = "point at infinity."

**Expected Text**
> the tangent line will be exactly vertical, in which case P\~3\~ = "point at infinity."

**Comment by wbnns** [comment]
@motorina0 

Thank you.
