### ISSUE TITLE
A calculation error for blocks generation rate in Chapter 7

### ISSUE THREAD

**Issue by zlog-in** [bitcoinbook/bitcoinbook#710]
> where <now {plus} 3 months> is a block height or time value estimated 3 months from the time the transaction is mined: current block height + 12,960 (blocks) or current Unix epoch time + 7,760,000 (seconds). For now, don’t worry about the DROP opcode that follows CHECKLOCKTIMEVERIFY; it will be explained shortly.

Hello, I might find a calculation error here for block generation. I thought the right sum for 3 months = 6 * 24 * 14 * 6 = 12,096 (blocks).

**Comment by simone-cominato** [comment]
> > where <now {plus} 3 months> is a block height or time value estimated 3 months from the time the transaction is mined: current block height + 12,960 (blocks) or current Unix epoch time + 7,760,000 (seconds). For now, don’t worry about the DROP opcode that follows CHECKLOCKTIMEVERIFY; it will be explained shortly.
> 
> Hello, I might find a calculation error here for block generation. I thought the right sum for 3 months = 6 * 24 * 14 * 6 = 12,096 (blocks).

Uhm... imho 12960 it's correct: 6 block/h * 24 h/day * 30 days/month * 3 months = 12960.

**Comment by zlog-in** [comment]
haaa... in my view a month = 2 half-month = 2 * 14 days = 28 days XD
Thanks for that info!
