### ISSUE TITLE
Ch06 - Transaction Pools

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#72]
4th paragraph - Second sentence:
"Any orphans found are pulled from the orphan pool and validated using the above checklist."

I don't see any checklist.

**Comment by edeykholt** [comment]
Also, "pulled" is a little ambiguous in this context.  Do we mean queried or culled (removed)?  Seems like first it would be queried and then removed once they are added to the transaction pool (in the next sentence)?

**Comment by enderminh** [comment]
It looks like Andreas is referring to the checklist that doesn't come later until chapter 8. I removed the reference and reworded this also per your second comment.
