### ISSUE TITLE
Chapter 2 description of transaction debits and credits analogy is backwards

### ISSUE THREAD

**Issue by edeykholt** [bitcoinbook/bitcoinbook#75]
In the text:
"Transactions are like lines in a double-entry bookkeeping ledger. In simple terms, each transaction contains one or more "inputs", which are debits against a bitcoin account. On the other side of the transaction, there are one or more "outputs", which are credits added to a bitcoin account. The inputs and outputs (debits and credits) do not necessarily add up to the same amount. Instead, outputs add up to slightly less than inputs and the difference represents an implied "transaction fee", a small payment collected by the miner who includes the transaction in the ledger. "

... debits and credits are backwards.  Although debits are on the left in T accounting, reductions to asset accounts are credits, not debits.   My suggested rewording, below, was rejected, so this section still needs to be addressed somehow.

Suggested text:
"-Transactions are like a journal entry record in a double-entry bookkeeping ledger. Each transaction contains:
 -
 -\* a set of one or more "inputs", each with an input address and value
 -\* a set of one or more "outputs", each with an output address and value
 -
 -The inputs are to become the reductions to bitcoin addresses, and the outputs increases to other bitcoin addresses.  The net inputs and net outputs must balance, with the exception of an optional implicit "transaction fee", a small output payment collected by the miner.  Similar to debits and credits in an accounting journal entry, the net amount (input values less output values less fee) must be zero."

**Comment by enderminh** [comment]
This is a larger text change, so assigning to Andreas for decision and wording.
