### ISSUE TITLE
Chapter 3 - Example 5: does not work for pruned nodes

### ISSUE THREAD

**Issue by Lobbelt** [bitcoinbook/bitcoinbook#758]
I'm running a pruned node myself, so for me the example code did not work as it was given. I had to change line 23 from

` raw_tx = p.getrawtransaction(txid)`

to

`raw_tx = p.getrawtransaction(txid, False, blockhash)`

(cf. [getrawtransaction documentation](https://developer.bitcoin.org/reference/rpc/getrawtransaction.html)).

Suggestion: maybe change code to the above or include a warning that the code may not work for those running a pruned node? 

Such users would also have to change the blockheight to a block that they are sure is included in their pruned copy, though... I just used the most recently mined block.

**Comment by wbnns** [comment]
@Lobbelt 

Thank you.
