### ISSUE TITLE
Chapter 3: gettransaction example only works with indexing turned on

### ISSUE THREAD

**Issue by cryptid11** [bitcoinbook/bitcoinbook#76]
seems that this command: "bitcoind gettransaction 9ca8f969bd3ef5ec2a8685660fdbf7a8bd365524c2e1fc66c309acbae2c14ae3" doesn't work anymore. Probably is for this reason
http://bitcoin.stackexchange.com/questions/9147/getrawtransaction-error-code-5

But I'm a noob in the Bitcoindev ecosystem, let me know what's the problem if not that!

**Comment by enderminh** [comment]
Yeah, I can confirm that this is happening.

This is in regards to the "bitcoind gettransaction 9ca8f969bd3ef5ec2a8685660fdbf7a8bd365524c2e1fc66c309acbae2c14ae3" example in Chapter 3 ("Exploring and decoding transactions").

We might have to update this text, or mention about indexing needing to be turned on. Re-assigning to Andreas.
