### ISSUE TITLE
Ch.07: clarification or context needed to understand P2WPKH & P2WSH

### ISSUE THREAD

**Issue by simsbluebox** [bitcoinbook/bitcoinbook#760]
The [Wallet construction of P2WPKH](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch07.asciidoc#wallet-construction-of-p2wpkh) section says:

> The sender has no way of knowing if the recipient’s wallet has the ability to construct segwit transactions and spend P2WPKH outputs.

And the [Upgrading to Segregated Witness](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch07.asciidoc#upgrading-to-segregated-witness) says:

> What may not be obvious from the example is that in practice, Alice’s wallet needs to know that Bob uses a segwit-aware wallet and can spend these outputs. Otherwise, if Bob’s wallet is not upgraded and Alice tries to make segwit payments to Bob, Bob’s wallet will not be able to detect these payments.

I just wanted to know for better understanding what I maybe missing out that these two definitions seems to me contradictory.

Thank you.

**Comment by rating89us** [comment]
It seems to me that the first section should be: 

> The **receiver** has no way of knowing if the **sender's** wallet has the ability to construct segwit transactions and spend P2WPKH outputs.

Because by looking the bc1 prefix in a native segwit (bech32) address, the (segwit-aware) sender knows that the receiver has the ability to construct segwit transactions and spend P2WPKH outputs.

**Comment by wbnns** [comment]
@simsbluebox @rating89us 

Thanks, updated.
