### ISSUE TITLE
Ch. 10: Link Isn't working + Paperback Edition reference missing

### ISSUE THREAD

**Issue by simsbluebox** [bitcoinbook/bitcoinbook#770]
In Chapter 10, [Coinbase Data section](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch10.asciidoc#coinbase-data):

> The first byte, 03, instructs the script execution engine to push the next three bytes onto the script stack (see [tx_script_ops_table_pushdata]).

Link (tx_script_ops_table_pushdata) isn't working.

And in the Paperback second edition, third release (2018-03-23), says:

> The first byte, 03, instructs the script execution engine to push the next three bytes onto the script stack (see Table B-1)

But I can't find any table with that name (In paperback edition tables, figures and examples have a different naming)

Thank you!

**Comment by rating89us** [comment]
In the printed version, Table B-1 is Table 1 in Appendix B "Transaction Script Language Operators, Constants, and Symbol".

In the online version, [tx_script_ops_table_pushdata] is Table 1 in Appendix "Transaction Script Language Operators, Constants, and Symbol" https://github.com/bitcoinbook/bitcoinbook/blob/develop/appdx-scriptops.asciidoc

**Comment by simsbluebox** [comment]
Thank you, @rating89us  !
