### ISSUE TITLE
Ch. 10: Minimum tx size: 100 vs 82 bytes

### ISSUE THREAD

**Issue by simsbluebox** [bitcoinbook/bitcoinbook#790]
The section [Independent Verification of Transactions](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch10.asciidoc#independent-verification-of-transactions) states:

> The transaction size in bytes is greater than or equal to 100

But considering [validation](https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L587) (via _[Why must transactions be no less than 82 bytes to be relayed?](https://github.com/chaincodelabs/study-groups/blob/master/p2p/ANSWERS.md)_) if I am understanding correctly, the actual minimum size would be 82 bytes. Would that be correct ?

Thank you!

**Comment by wbnns** [comment]
@simsbluebox 

Nice catch, fixed!
