### ISSUE TITLE
Chapter 8 checklists should follow parallel construction

### ISSUE THREAD

**Issue by edeykholt** [bitcoinbook/bitcoinbook#85]
In the sections "Independent Verification of Transactions" and "Validating a New Block" the checklists would read better if they were worded similarly.  I suggest prefacing the checklist with "Each node verified every transaction against a long checklist of criteria that must all evaluate true; otherwise, the transaction is rejected:".

Then, each criteria would be re-worded.  E.g., instead of "Check the syntactic correctness of the transaction's data structure" say "The transaction's syntax and data structure is correct."

**Comment by enderminh** [comment]
I've reworded a good majority of them, but some do sound better in its current form.
