### ISSUE TITLE
ch01: Consider replacing Mycelium Wallet

### ISSUE THREAD

**Issue by wbnns** [bitcoinbook/bitcoinbook#854]
On Android seems like the quality of the app has diminished according to [reviews](https://play.google.com/store/apps/details?id=com.mycelium.wallet) in the Play Store. It's no longer available for iOS.

There may be some other wallets of a high caliber that could be good candidates to mention.

**Comment by aantonop** [comment]
I think Bluewallet <https://bluewallet.io/features/> (iOS, Android) might
be a great option, for newbies and experienced users. It is non-custodial,
BIP39, open source, supports all address formats, fee management, RBF and
CPFP, Lightning and lots more.

Thoughts?

**Comment by wbnns** [comment]
I like Bluewallet also.

**Comment by krupawan5618** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/866

**Comment by wbnns** [comment]
@krupawan5618 

Awesome! Thanks for taking the initiative on this! Let's give it a few more days just to make sure there isn't any other feedback from the community.

**Comment by wbnns** [comment]
Resolved by #866.
