### ISSUE TITLE
ch01: Consider updating section on methods for getting bitcoin

### ISSUE THREAD

**Issue by wbnns** [bitcoinbook/bitcoinbook#856]
Reference:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/1130872/110212749-3ccd8800-7e9d-11eb-936c-cce46597e5c8.png">

Reason:

The first method, going to a Bitcoin meetup, is more difficult now as a result of coronavirus, and many of them are now online only events (one should be wary of getting bitcoin from someone they meet online if there isn't some form of escrow).

There's a mention of using a reputable exchange, but it's at the bottom; not sure if that is intentional. But just wanted to raise the issue in case it's worth revisiting / reconsidering. Maybe list that first, even above Local Bitcoins?

**Comment by krupawan5618** [comment]
with regard to this issue, details on acquiring bitcoin have been consolidated and ported from LnBook

**Comment by wbnns** [comment]
@krupawan5618 

Thanks for pointing this out. 👍
