### ISSUE TITLE
Updating exchange rate references throughout book

### ISSUE THREAD

**Issue by wbnns** [bitcoinbook/bitcoinbook#858]
We should maybe consider updating price references in the book, to help users understand the fractional amounts they will be dealing with more redundantly.

For example, in Chapter 1, BTC/USD is $100. The user is paying $10 for .1. Of course, they can already see here that they are getting a fractional amount. But most likely, for smaller transactions they should get used to much smaller decimal places from the get-go.

**Comment by krupawan5618** [comment]
Many of the examples in the book rely on the example provided; perhaps a TIP box stating that the prices of bitcoin in the book should not be considered as up to date? This would fit right in the "Finding the Price of Bitcoin" section. The numbers provided by the example are easy to work with. Thoughts?

**Comment by krupawan5618** [comment]
Was reading 02 Getting Started of Mastering the Lightning Network and noticed that there is a Tip box that might serve as a reference or guidance to addressing the discrepancy referenced by this issue.


Tip | Did you notice that the channel amount seems to have changed? It hasn’t: the channel contains 0.018 BTC, but in the time between screenshots the BTC exchange rate changed, so the USD value is different. You can choose to show balances in BTC or USD, but keep in mind that USD values are calculated in real-time and will change!
-- | --

**Comment by krupawan5618** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/872

regarding exchange rate discrepancy

**Comment by krupawan5618** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/873

regarding satoshis
