### ISSUE TITLE
Chapter 8 - code example missing?

### ISSUE THREAD

**Issue by edeykholt** [bitcoinbook/bitcoinbook#86]
Following the paragraph "With these calculations, Jing's node then constructs the generation transaction to pay himself 25.09094928 bitcoin. The generation transaction is the first transaction in the block, so we can see it in more detail using the Bitcoin Core command-line interface:"

is there supposed to be sample code?

**Comment by enderminh** [comment]
Looks like the sample code that shows that the generation transaction is indeed the first transaction in the block is missing. Re-assigning to Andreas.
