### ISSUE TITLE
ch01: Expand upon importance on mnemonic phrases in the creation of a new wallet

### ISSUE THREAD

**Issue by krupawan5618** [bitcoinbook/bitcoinbook#867]
In reading 02 Getting Started of Mastering the Lightning Network, I recognize that in this first chapter there is not enough of an emphasis or clarity provided to mnemonic phrases. Can consider porting over the best parts of the Lightning Network chapter into this first chapter for completeness. 

https://github.com/lnbook/lnbook/blob/develop/02_getting_started.asciidoc

**Comment by wbnns** [comment]
@krupawan5618

Sure, go for it. 👍

**Comment by krupawan5618** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/871
