### ISSUE TITLE
Ch4: Keys, Address: Bitcoinpaperwallet.com has been stealing people's funds left and right

### ISSUE THREAD

**Issue by Bamskki** [bitcoinbook/bitcoinbook#869]
Please remove everything related to Bitcoinpaperwallet.com
https://www.coindesk.com/bitcoinpaperwallet-back-door-missing-funds-research

**Comment by wbnns** [comment]
@Bamskki 

Hello, thanks for the mention. I took a look and do not see any mentions to the site.

**Comment by Bamskki** [comment]
It has been removed by someone. I have a very recent copy of the repo and I can see it but not on GitHub anymore so that's good :)

**Comment by wbnns** [comment]
Ok, great. 👍

**Comment by aantonop** [comment]
I removed it in #07da92ac9563d3b8b3faf09b908d4463cbcb3540
