### ISSUE TITLE
Chapter 8 - example paragraph order

### ISSUE THREAD

**Issue by edeykholt** [bitcoinbook/bitcoinbook#87]
In the text:
"In the example above, the winning "nonce" is 13 and this result can be confirmed by anyone independently."

This actually is not referring to an example (analogy) immediately above, but the example a few paragraphs before that.  Consider changing the paragraph order.

**Comment by enderminh** [comment]
When I read this text, I thought this was fine and wasn't confused. However, I changed "In the example above" to "In the hashing example above" to disambiguate just in case.
