### ISSUE TITLE
ch02: Incorporating additional corrections into mbc2_0209.png

### ISSUE THREAD

**Issue by wbnns** [bitcoinbook/bitcoinbook#876]
Corrections:

1. **Confirmations (Blocks deep**) should be **Confirmations (Block depth)** see https://en.bitcoin.it/wiki/Confirmation
2. **Blocks (Blockchain)** should be **Blocks (Block height)** see https://www.investopedia.com/terms/b/block-height.asp 
3. **Block 277315** should be deleted and instead of it there should be **"Mempool Alice's transaction"** as it wrong that this block has the transaction with 0 confirmations - it is the mempool.
4.  **The arrows** connecting the blocks should go **upwards** not **downwards** as the block count goes up.

Cc: @montvid @rating89us

**Comment by rating89us** [comment]
> Confirmations (Blocks deep) should be Confirmations (Block depth)

6 confirmations means 6 blocks deep ("confirmation" could be used as a synonym for "blocks deep")

> Blocks (Blockchain) should be Blocks (Block height)

The idea here is to replicate the blockchain of ch10, not to teach the block height concept:
![image](https://user-images.githubusercontent.com/45968869/110788655-2e9db400-826f-11eb-9c84-2b6956a36de0.png). 

This is why I used arrows in the same direction:
![image](https://user-images.githubusercontent.com/45968869/110789233-ec28a700-826f-11eb-920d-4bc3d998e872.png)

> The arrows connecting the blocks should go upwards not downwards as the block count goes up.

See above

> Block 277315 should be deleted and instead of it there should be "Mempool Alice's transaction" as it wrong that this block has the transaction with 0 confirmations - it is the mempool.

Same as above. The "Blocks" column represent the Blockchain as seen by most nodes of the network. What I meant was: "After block 2773165 was created, Alice's transaction was included in the mempool, before block 277316 was mined."

**Comment by rating89us** [comment]
I suggest we add this additional image to explain block depth, block height and difficulty:
![image](https://user-images.githubusercontent.com/45968869/110792759-12e8dc80-8274-11eb-909c-bc887f339fee.png)

What do you think?

**Comment by montvid** [comment]
> 6 confirmations means 6 blocks deep ("confirmation" could be used as a synonym for "blocks deep")

Are you aware of blockchain technical language if not please read again https://en.bitcoin.it/wiki/Confirmation - "blocks deep" -> "Block depth"

> The idea here is to replicate the blockchain of ch10, not to teach the block height concept:

Your diagram teaches the block height concept already - it just needs a correct name. Well you are replacing the diagram in chapter 2 so it has to have the same information from the abandoned diagram here https://howieliux.github.io/assets/others/Mastering_bitcoin/images/mbc2_0209.png

> What I meant was: "After block 2773165 was created, Alice's transaction was included in the mempool, before block 277316 was mined."

I understand what you did but it is confusing to put "0 confirmations" next to block "2773165" see:
![2](https://user-images.githubusercontent.com/23270059/110793280-1d5ba400-827d-11eb-8b36-4d5ef154f4c1.png)

- 0 confiramtion should be put next to "Mempool Alice's transaction" 
- The same here - it is confusing as Alice's transaction creation has nothing to do with block 2773165:
![3](https://user-images.githubusercontent.com/23270059/110793719-9fe46380-827d-11eb-8102-b91163c809d2.png)

**Your original diagram style is fine** no need for another diagram, just minor corrections.

**Comment by montvid** [comment]
My masterpiece lol :smile: A picture is worth a 1000 words heheh, btw could you explain more why are you using arrows downwards? What does it symbolize? Btw I am talking about **chapter 2 diagram** as it was my original bug report about it.

**Comment by montvid** [comment]
ah, now I remember the arrows are the chain that links all the blocks to the first block! So instead of the name Block - It should be **blockchain** or better still **chain of blocks**. Ok the arrows are not a mistake!!!
**chapter 2 diagram**
![5](https://user-images.githubusercontent.com/23270059/110804437-d96e9c00-8288-11eb-903c-a2b02f9d7993.png)

**Comment by montvid** [comment]
Per https://en.bitcoin.it/wiki/Confirmation i would go for Extremely Easy -> Very Easy -> Normal -> Hard -> Very Hard -> Extremely Hard - or better still not use words at all as it **depends on the hash power of the attacker**. As in https://howieliux.github.io/assets/others/Mastering_bitcoin/images/mbc2_0209.png

One could write **hash power of the attacker** on the difficulty arrow instead of easy-hard.

**Comment by rating89us** [comment]
Thanks for your feedback. I did some of your suggested changes in #878 (see below). I will wait for additional opinions from other users before doing further modifications.

![image](https://user-images.githubusercontent.com/45968869/110814043-5c8ff200-8289-11eb-84aa-f58b7e3c4672.png)

**Comment by montvid** [comment]
I see it is a learning experience for you. See https://www.investopedia.com/terms/b/block-height.asp

> The total height of the blockchain is taken to be the height of the most recent block, or the highest block, in the chain.
1. The last diagram is wrong as the **current block height** is 277319 the **mined block** not the candidate block.
2. 277315 block should be aligned with 277315 height in the diagram
3. As said before I would abandon the easy - hard scale as technically it is incorrect. See https://en.bitcoin.it/wiki/Confirmation 

>  Note that in the reality of bitcoin mining today, more than 6 confirmations are required. (60 confirmations to have <1% odds of succeeding against an entity with 40% hash power). See Section 11 of the (https://bitcoin.org/bitcoin.pdf bitcoin whitepaper) for the AttackerSuccessProbability formula. 

4. Depth and difficulty should be next to each other.

**Comment by rating89us** [comment]
Fixed. Changed to harder / easier in difficulty (terminology used in ch10 text)
![image](https://user-images.githubusercontent.com/45968869/110831456-8b629400-829a-11eb-9606-368ee85d6893.png)

**Comment by montvid** [comment]
ok,  i just would agree to 1 blockchain, 2 block height, 3 block depth, 4 difficulty. 
What is the meaning of this? 
![10](https://user-images.githubusercontent.com/23270059/110834945-d682a400-82a6-11eb-975d-d22382bd182a.png)

**Comment by krupawan5618** [comment]
I love the diagram, but I wonder how this would look if we just removed the block height arrow altogether and put a comment of 'current block height' under 227319? The numbering is on the blocks themselves, maybe in the image footer state that the block height is denoted by the number in the blocks? This may help the image appear less 'busy' overall, just a thought 👍 

Otherwise, yes I think that block height should be next to the blockchain itself, maybe even on the left side so it goes 1 height, 2 block chain, 3 block depth, 4 difficulty?

Also, should read '0 confirmation**s**' and '0 block**s** deep'

![memes](https://user-images.githubusercontent.com/3332001/110841971-87238000-8274-11eb-9c6f-34acac3b8c33.png)

**Comment by rating89us** [comment]
Updated. Tell me what you think about this version: 
![image](https://user-images.githubusercontent.com/45968869/110861441-6e3fbc80-82be-11eb-9251-2e956f90cd24.png)

**Comment by krupawan5618** [comment]
@rating89us might I ask what software you are using to generate these nice diagrams? Thank you

**Comment by montvid** [comment]
Everything is technically correct now. I don't know how this will fit in a printed book but the diagram is foolproof now. Thanks @rating89us.

**Comment by wbnns** [comment]
Thanks everybody (and especially @rating89us for all of the iterations / updates).

Are we all in agreement that #878 (the updated graphic) is good to be merged?

**Comment by montvid** [comment]
Yes, good to merge. Thanks everyone.
