### ISSUE TITLE
Typo in ch07, "a unspent" is used instead of "an unspent".

### ISSUE THREAD

**Issue by lubomr** [bitcoinbook/bitcoinbook#883]
![image](https://user-images.githubusercontent.com/22976567/111020381-0a0c1e00-83ce-11eb-84e7-5ce7514a6d8e.png)

**Comment by krupawan5618** [comment]
https://github.com/bitcoinbook/bitcoinbook/pull/885

**Comment by krupawan5618** [comment]
resolved from merge, consider closing
