### ISSUE TITLE
Chapter 8 - Aggregating Transactions into Blocks

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#92]
In 4th paragraph:
"...Jing’s node has assembled a chain of 277,314 blocks. Jing’s node is listening for transactions, trying to mine a new block and also listening for blocks discovered by other nodes. As Jing’s node is mining, it receives block 277,315 through the bitcoin network."

If there are 277,314 blocks in the chain (including the genesis block on height 0), the last block would have block height 277,313 .Thus, the next block received would be 277,314 - Not 277.315. 
To fix this, I would suggest changing the paragraph to:
"...Jing’s node has assembled a chain of 277,315 blocks...."

**Comment by enderminh** [comment]
I've resolved the issue by changing "Jing’s node has assembled a chain of 277,314 blocks" to "Jing's node has assembled a chain up to block 277,314."
