### ISSUE TITLE
Chapter 8 - Difficulty Representation

### ISSUE THREAD

**Issue by erikwam** [bitcoinbook/bitcoinbook#93]
"...
 ⇒ target = 238,348 \* 2^176
 ⇒ target = 9,223,372,036,854,775,807"

Where did "9,223,372,036,854,775,807" come from?

I get: 238,348 \* 2^176 =
22,829,202,948,393,929,850,749,706,076,701,368,331,072,452,018,388,575,715,328

**Comment by enderminh** [comment]
It looks like the error came from typing in the formula on a Mac scientific calculator, getting the correct value in scientific notation, but when switching to the programming view, the Mac calculator converts it incorrectly.

Thanks for reporting. I fixed it.
