### ISSUE TITLE
Estimate total number of hashes Chapter 10 

### ISSUE THREAD

**Issue by AndreaP314** [bitcoinbook/bitcoinbook#937]
First of all, thank you for writing this book, it is really great! 

I am writing since I could not understand an estimate in Chapter 10. In particular,

"With this level of difficulty, a single miner processing 1 trillion hashes per second (1 terahash per second or 1 TH/sec) would only find a solution once every 8,496 blocks or once every 59 days, on average."

If I am correct

8496 x 10 / (60*24) = 59days

and the total hashes tried are

(59 x 24 x 60 x 60) x 10^12= 5097600000000000000 ~ 5.10 x 10^18

However I do not understand the relation between 5.10*10^18 and the target which (as written in the book) is equal to

22829202948393929850749706076701368331072452018388575715328 - decimal 0x0000000000000003A30C00000000000000000000000000000000000000000000 - hexadecimal

Just as a reference I also write the number just before (target-1)

22829202948393929850749706076701368331072452018388575715327 - decimal 0x0000000000000003A30BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF - hexadecimal

Could you help me understand the details of the 59days estimate given the target?

I am confused since the target has 15 zeros but

5097600000000000000 / 16^8 = 1186877489 is an integer

while

5097600000000000000 / 16^9 = 74179843.07

Thank you again for your time!

**Comment by AndreaP314** [comment]
I have just realized the answer is available [here](https://bitcoin.stackexchange.com/questions/43111/how-was-59-days-determined-with-1-th-sec-from-mastering-bitcoin?rq=1).

**Comment by wbnns** [comment]
Glad you were able to get the info you need. :)
