### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by 0bs72** [bitcoinbook/bitcoinbook#978]
This is a cool project and seems to be active; props for that.

Not an 'issue' as such; just a couple of questions.

1. Is there any reason (e.g: copyright issues) for the graphic icons having not been used for the *Tip / Note / Warning* sections?
2. Why has this been presented in asciidoc format, as opposed to regular html files?

**Comment by aantonop** [comment]
1) The graphic icons are used in the ebook renderings that I offer for
sale. Depending on how you render it, you can use a variety of fonts and
icons. The O'Reilly icons are proprietary and cannot be used

2) The book is written in ASCIIdoc directly. HTML can be produced from it
but the "source code" you see here is the original manuscript that produces
the commercial book sold on Amazon

**Comment by 0bs72** [comment]
Thank you very much for the rapid response, as well as the Book and resources contained therein.

My best regards to you.
